# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from chart_hop_python_sdk import schemas  # noqa: F401


class BudgetPool(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "sourceField",
            "updateId",
            "appliedField",
            "basisType",
            "createId",
            "compReviewId",
            "updateAt",
            "id",
            "label",
            "createAt",
            "orgId",
        }
        
        class properties:
            id = schemas.StrSchema
            orgId = schemas.StrSchema
            compReviewId = schemas.StrSchema
            label = schemas.StrSchema
            appliedField = schemas.StrSchema
            sourceField = schemas.StrSchema
            
            
            class basisType(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def CUSTOM(cls):
                    return cls("CUSTOM")
                
                @schemas.classproperty
                def FIXED(cls):
                    return cls("FIXED")
                
                @schemas.classproperty
                def CUSTOM_FIXED(cls):
                    return cls("CUSTOM_FIXED")
                
                @schemas.classproperty
                def PERCENTAGE(cls):
                    return cls("PERCENTAGE")
                
                @schemas.classproperty
                def CUSTOM_PERCENTAGE(cls):
                    return cls("CUSTOM_PERCENTAGE")
            createId = schemas.StrSchema
            createAt = schemas.StrSchema
            updateId = schemas.StrSchema
            updateAt = schemas.StrSchema
            participantsExpr = schemas.StrSchema
        
            @staticmethod
            def fixedAmount() -> typing.Type['Money']:
                return Money
            fixedValue = schemas.NumberSchema
        
            @staticmethod
            def basisFieldMatrix() -> typing.Type['BasisFieldMatrix']:
                return BasisFieldMatrix
        
            @staticmethod
            def fixedBudgetMap() -> typing.Type['BudgetPoolFixedBudgetMap']:
                return BudgetPoolFixedBudgetMap
            basisExpr = schemas.StrSchema
            defaultCurrency = schemas.StrSchema
            deleteId = schemas.StrSchema
            deleteAt = schemas.StrSchema
            __annotations__ = {
                "id": id,
                "orgId": orgId,
                "compReviewId": compReviewId,
                "label": label,
                "appliedField": appliedField,
                "sourceField": sourceField,
                "basisType": basisType,
                "createId": createId,
                "createAt": createAt,
                "updateId": updateId,
                "updateAt": updateAt,
                "participantsExpr": participantsExpr,
                "fixedAmount": fixedAmount,
                "fixedValue": fixedValue,
                "basisFieldMatrix": basisFieldMatrix,
                "fixedBudgetMap": fixedBudgetMap,
                "basisExpr": basisExpr,
                "defaultCurrency": defaultCurrency,
                "deleteId": deleteId,
                "deleteAt": deleteAt,
            }
    
    sourceField: MetaOapg.properties.sourceField
    updateId: MetaOapg.properties.updateId
    appliedField: MetaOapg.properties.appliedField
    basisType: MetaOapg.properties.basisType
    createId: MetaOapg.properties.createId
    compReviewId: MetaOapg.properties.compReviewId
    updateAt: MetaOapg.properties.updateAt
    id: MetaOapg.properties.id
    label: MetaOapg.properties.label
    createAt: MetaOapg.properties.createAt
    orgId: MetaOapg.properties.orgId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["orgId"]) -> MetaOapg.properties.orgId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["compReviewId"]) -> MetaOapg.properties.compReviewId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["label"]) -> MetaOapg.properties.label: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["appliedField"]) -> MetaOapg.properties.appliedField: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sourceField"]) -> MetaOapg.properties.sourceField: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["basisType"]) -> MetaOapg.properties.basisType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createId"]) -> MetaOapg.properties.createId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createAt"]) -> MetaOapg.properties.createAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updateId"]) -> MetaOapg.properties.updateId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updateAt"]) -> MetaOapg.properties.updateAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["participantsExpr"]) -> MetaOapg.properties.participantsExpr: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fixedAmount"]) -> 'Money': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fixedValue"]) -> MetaOapg.properties.fixedValue: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["basisFieldMatrix"]) -> 'BasisFieldMatrix': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fixedBudgetMap"]) -> 'BudgetPoolFixedBudgetMap': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["basisExpr"]) -> MetaOapg.properties.basisExpr: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["defaultCurrency"]) -> MetaOapg.properties.defaultCurrency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deleteId"]) -> MetaOapg.properties.deleteId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deleteAt"]) -> MetaOapg.properties.deleteAt: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "orgId", "compReviewId", "label", "appliedField", "sourceField", "basisType", "createId", "createAt", "updateId", "updateAt", "participantsExpr", "fixedAmount", "fixedValue", "basisFieldMatrix", "fixedBudgetMap", "basisExpr", "defaultCurrency", "deleteId", "deleteAt", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["orgId"]) -> MetaOapg.properties.orgId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["compReviewId"]) -> MetaOapg.properties.compReviewId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["label"]) -> MetaOapg.properties.label: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["appliedField"]) -> MetaOapg.properties.appliedField: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sourceField"]) -> MetaOapg.properties.sourceField: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["basisType"]) -> MetaOapg.properties.basisType: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createId"]) -> MetaOapg.properties.createId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createAt"]) -> MetaOapg.properties.createAt: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updateId"]) -> MetaOapg.properties.updateId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updateAt"]) -> MetaOapg.properties.updateAt: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["participantsExpr"]) -> typing.Union[MetaOapg.properties.participantsExpr, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fixedAmount"]) -> typing.Union['Money', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fixedValue"]) -> typing.Union[MetaOapg.properties.fixedValue, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["basisFieldMatrix"]) -> typing.Union['BasisFieldMatrix', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fixedBudgetMap"]) -> typing.Union['BudgetPoolFixedBudgetMap', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["basisExpr"]) -> typing.Union[MetaOapg.properties.basisExpr, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["defaultCurrency"]) -> typing.Union[MetaOapg.properties.defaultCurrency, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deleteId"]) -> typing.Union[MetaOapg.properties.deleteId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deleteAt"]) -> typing.Union[MetaOapg.properties.deleteAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "orgId", "compReviewId", "label", "appliedField", "sourceField", "basisType", "createId", "createAt", "updateId", "updateAt", "participantsExpr", "fixedAmount", "fixedValue", "basisFieldMatrix", "fixedBudgetMap", "basisExpr", "defaultCurrency", "deleteId", "deleteAt", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        sourceField: typing.Union[MetaOapg.properties.sourceField, str, ],
        updateId: typing.Union[MetaOapg.properties.updateId, str, ],
        appliedField: typing.Union[MetaOapg.properties.appliedField, str, ],
        basisType: typing.Union[MetaOapg.properties.basisType, str, ],
        createId: typing.Union[MetaOapg.properties.createId, str, ],
        compReviewId: typing.Union[MetaOapg.properties.compReviewId, str, ],
        updateAt: typing.Union[MetaOapg.properties.updateAt, str, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        label: typing.Union[MetaOapg.properties.label, str, ],
        createAt: typing.Union[MetaOapg.properties.createAt, str, ],
        orgId: typing.Union[MetaOapg.properties.orgId, str, ],
        participantsExpr: typing.Union[MetaOapg.properties.participantsExpr, str, schemas.Unset] = schemas.unset,
        fixedAmount: typing.Union['Money', schemas.Unset] = schemas.unset,
        fixedValue: typing.Union[MetaOapg.properties.fixedValue, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        basisFieldMatrix: typing.Union['BasisFieldMatrix', schemas.Unset] = schemas.unset,
        fixedBudgetMap: typing.Union['BudgetPoolFixedBudgetMap', schemas.Unset] = schemas.unset,
        basisExpr: typing.Union[MetaOapg.properties.basisExpr, str, schemas.Unset] = schemas.unset,
        defaultCurrency: typing.Union[MetaOapg.properties.defaultCurrency, str, schemas.Unset] = schemas.unset,
        deleteId: typing.Union[MetaOapg.properties.deleteId, str, schemas.Unset] = schemas.unset,
        deleteAt: typing.Union[MetaOapg.properties.deleteAt, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BudgetPool':
        return super().__new__(
            cls,
            *args,
            sourceField=sourceField,
            updateId=updateId,
            appliedField=appliedField,
            basisType=basisType,
            createId=createId,
            compReviewId=compReviewId,
            updateAt=updateAt,
            id=id,
            label=label,
            createAt=createAt,
            orgId=orgId,
            participantsExpr=participantsExpr,
            fixedAmount=fixedAmount,
            fixedValue=fixedValue,
            basisFieldMatrix=basisFieldMatrix,
            fixedBudgetMap=fixedBudgetMap,
            basisExpr=basisExpr,
            defaultCurrency=defaultCurrency,
            deleteId=deleteId,
            deleteAt=deleteAt,
            _configuration=_configuration,
            **kwargs,
        )

from chart_hop_python_sdk.model.basis_field_matrix import BasisFieldMatrix
from chart_hop_python_sdk.model.budget_pool_fixed_budget_map import BudgetPoolFixedBudgetMap
from chart_hop_python_sdk.model.money import Money
