# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from chart_hop_python_sdk import schemas  # noqa: F401


class CreateCategory(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "label",
        }
        
        class properties:
            label = schemas.StrSchema
            orgId = schemas.StrSchema
        
            @staticmethod
            def fieldIds() -> typing.Type['CreateCategoryFieldIds']:
                return CreateCategoryFieldIds
        
            @staticmethod
            def nativeFields() -> typing.Type['CreateCategoryNativeFields']:
                return CreateCategoryNativeFields
            __annotations__ = {
                "label": label,
                "orgId": orgId,
                "fieldIds": fieldIds,
                "nativeFields": nativeFields,
            }
    
    label: MetaOapg.properties.label
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["label"]) -> MetaOapg.properties.label: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["orgId"]) -> MetaOapg.properties.orgId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fieldIds"]) -> 'CreateCategoryFieldIds': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nativeFields"]) -> 'CreateCategoryNativeFields': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["label", "orgId", "fieldIds", "nativeFields", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["label"]) -> MetaOapg.properties.label: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["orgId"]) -> typing.Union[MetaOapg.properties.orgId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fieldIds"]) -> typing.Union['CreateCategoryFieldIds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nativeFields"]) -> typing.Union['CreateCategoryNativeFields', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["label", "orgId", "fieldIds", "nativeFields", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        label: typing.Union[MetaOapg.properties.label, str, ],
        orgId: typing.Union[MetaOapg.properties.orgId, str, schemas.Unset] = schemas.unset,
        fieldIds: typing.Union['CreateCategoryFieldIds', schemas.Unset] = schemas.unset,
        nativeFields: typing.Union['CreateCategoryNativeFields', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CreateCategory':
        return super().__new__(
            cls,
            *args,
            label=label,
            orgId=orgId,
            fieldIds=fieldIds,
            nativeFields=nativeFields,
            _configuration=_configuration,
            **kwargs,
        )

from chart_hop_python_sdk.model.create_category_field_ids import CreateCategoryFieldIds
from chart_hop_python_sdk.model.create_category_native_fields import CreateCategoryNativeFields
