# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from chart_hop_python_sdk import schemas  # noqa: F401


class CreateCompBand(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "color",
            "baseInterval",
            "label",
            "jobLevel",
        }
        
        class properties:
            label = schemas.StrSchema
            color = schemas.StrSchema
        
            @staticmethod
            def baseInterval() -> typing.Type['EnumValue']:
                return EnumValue
            jobLevel = schemas.StrSchema
        
            @staticmethod
            def baseCompMax() -> typing.Type['Money']:
                return Money
        
            @staticmethod
            def baseCompMid() -> typing.Type['Money']:
                return Money
        
            @staticmethod
            def baseCompMin() -> typing.Type['Money']:
                return Money
            baseSpread = schemas.NumberSchema
        
            @staticmethod
            def baseTargetPay() -> typing.Type['Money']:
                return Money
            baseTargetPayPercentile = schemas.NumberSchema
            equityTargetShares = schemas.NumberSchema
            equityTargetPercentOfBase = schemas.NumberSchema
            equityTargetValue = schemas.NumberSchema
        
            @staticmethod
            def variableValue() -> typing.Type['Money']:
                return Money
            variablePercentOfBase = schemas.NumberSchema
            jobTierOneField = schemas.StrSchema
            jobTierTwoField = schemas.StrSchema
            jobTierThreeField = schemas.StrSchema
            __annotations__ = {
                "label": label,
                "color": color,
                "baseInterval": baseInterval,
                "jobLevel": jobLevel,
                "baseCompMax": baseCompMax,
                "baseCompMid": baseCompMid,
                "baseCompMin": baseCompMin,
                "baseSpread": baseSpread,
                "baseTargetPay": baseTargetPay,
                "baseTargetPayPercentile": baseTargetPayPercentile,
                "equityTargetShares": equityTargetShares,
                "equityTargetPercentOfBase": equityTargetPercentOfBase,
                "equityTargetValue": equityTargetValue,
                "variableValue": variableValue,
                "variablePercentOfBase": variablePercentOfBase,
                "jobTierOneField": jobTierOneField,
                "jobTierTwoField": jobTierTwoField,
                "jobTierThreeField": jobTierThreeField,
            }
    
    color: MetaOapg.properties.color
    baseInterval: 'EnumValue'
    label: MetaOapg.properties.label
    jobLevel: MetaOapg.properties.jobLevel
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["label"]) -> MetaOapg.properties.label: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["color"]) -> MetaOapg.properties.color: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["baseInterval"]) -> 'EnumValue': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobLevel"]) -> MetaOapg.properties.jobLevel: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["baseCompMax"]) -> 'Money': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["baseCompMid"]) -> 'Money': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["baseCompMin"]) -> 'Money': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["baseSpread"]) -> MetaOapg.properties.baseSpread: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["baseTargetPay"]) -> 'Money': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["baseTargetPayPercentile"]) -> MetaOapg.properties.baseTargetPayPercentile: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["equityTargetShares"]) -> MetaOapg.properties.equityTargetShares: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["equityTargetPercentOfBase"]) -> MetaOapg.properties.equityTargetPercentOfBase: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["equityTargetValue"]) -> MetaOapg.properties.equityTargetValue: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["variableValue"]) -> 'Money': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["variablePercentOfBase"]) -> MetaOapg.properties.variablePercentOfBase: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobTierOneField"]) -> MetaOapg.properties.jobTierOneField: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobTierTwoField"]) -> MetaOapg.properties.jobTierTwoField: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobTierThreeField"]) -> MetaOapg.properties.jobTierThreeField: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["label", "color", "baseInterval", "jobLevel", "baseCompMax", "baseCompMid", "baseCompMin", "baseSpread", "baseTargetPay", "baseTargetPayPercentile", "equityTargetShares", "equityTargetPercentOfBase", "equityTargetValue", "variableValue", "variablePercentOfBase", "jobTierOneField", "jobTierTwoField", "jobTierThreeField", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["label"]) -> MetaOapg.properties.label: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["color"]) -> MetaOapg.properties.color: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["baseInterval"]) -> 'EnumValue': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobLevel"]) -> MetaOapg.properties.jobLevel: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["baseCompMax"]) -> typing.Union['Money', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["baseCompMid"]) -> typing.Union['Money', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["baseCompMin"]) -> typing.Union['Money', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["baseSpread"]) -> typing.Union[MetaOapg.properties.baseSpread, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["baseTargetPay"]) -> typing.Union['Money', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["baseTargetPayPercentile"]) -> typing.Union[MetaOapg.properties.baseTargetPayPercentile, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["equityTargetShares"]) -> typing.Union[MetaOapg.properties.equityTargetShares, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["equityTargetPercentOfBase"]) -> typing.Union[MetaOapg.properties.equityTargetPercentOfBase, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["equityTargetValue"]) -> typing.Union[MetaOapg.properties.equityTargetValue, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["variableValue"]) -> typing.Union['Money', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["variablePercentOfBase"]) -> typing.Union[MetaOapg.properties.variablePercentOfBase, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobTierOneField"]) -> typing.Union[MetaOapg.properties.jobTierOneField, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobTierTwoField"]) -> typing.Union[MetaOapg.properties.jobTierTwoField, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobTierThreeField"]) -> typing.Union[MetaOapg.properties.jobTierThreeField, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["label", "color", "baseInterval", "jobLevel", "baseCompMax", "baseCompMid", "baseCompMin", "baseSpread", "baseTargetPay", "baseTargetPayPercentile", "equityTargetShares", "equityTargetPercentOfBase", "equityTargetValue", "variableValue", "variablePercentOfBase", "jobTierOneField", "jobTierTwoField", "jobTierThreeField", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        color: typing.Union[MetaOapg.properties.color, str, ],
        baseInterval: 'EnumValue',
        label: typing.Union[MetaOapg.properties.label, str, ],
        jobLevel: typing.Union[MetaOapg.properties.jobLevel, str, ],
        baseCompMax: typing.Union['Money', schemas.Unset] = schemas.unset,
        baseCompMid: typing.Union['Money', schemas.Unset] = schemas.unset,
        baseCompMin: typing.Union['Money', schemas.Unset] = schemas.unset,
        baseSpread: typing.Union[MetaOapg.properties.baseSpread, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        baseTargetPay: typing.Union['Money', schemas.Unset] = schemas.unset,
        baseTargetPayPercentile: typing.Union[MetaOapg.properties.baseTargetPayPercentile, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        equityTargetShares: typing.Union[MetaOapg.properties.equityTargetShares, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        equityTargetPercentOfBase: typing.Union[MetaOapg.properties.equityTargetPercentOfBase, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        equityTargetValue: typing.Union[MetaOapg.properties.equityTargetValue, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        variableValue: typing.Union['Money', schemas.Unset] = schemas.unset,
        variablePercentOfBase: typing.Union[MetaOapg.properties.variablePercentOfBase, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        jobTierOneField: typing.Union[MetaOapg.properties.jobTierOneField, str, schemas.Unset] = schemas.unset,
        jobTierTwoField: typing.Union[MetaOapg.properties.jobTierTwoField, str, schemas.Unset] = schemas.unset,
        jobTierThreeField: typing.Union[MetaOapg.properties.jobTierThreeField, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CreateCompBand':
        return super().__new__(
            cls,
            *args,
            color=color,
            baseInterval=baseInterval,
            label=label,
            jobLevel=jobLevel,
            baseCompMax=baseCompMax,
            baseCompMid=baseCompMid,
            baseCompMin=baseCompMin,
            baseSpread=baseSpread,
            baseTargetPay=baseTargetPay,
            baseTargetPayPercentile=baseTargetPayPercentile,
            equityTargetShares=equityTargetShares,
            equityTargetPercentOfBase=equityTargetPercentOfBase,
            equityTargetValue=equityTargetValue,
            variableValue=variableValue,
            variablePercentOfBase=variablePercentOfBase,
            jobTierOneField=jobTierOneField,
            jobTierTwoField=jobTierTwoField,
            jobTierThreeField=jobTierThreeField,
            _configuration=_configuration,
            **kwargs,
        )

from chart_hop_python_sdk.model.enum_value import EnumValue
from chart_hop_python_sdk.model.money import Money
