# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from chart_hop_python_sdk import schemas  # noqa: F401


class OrgCount(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "startingCount",
            "departingCount",
            "jobCount",
            "personCount",
        }
        
        class properties:
            jobCount = schemas.Int64Schema
            personCount = schemas.Int64Schema
            startingCount = schemas.Int64Schema
            departingCount = schemas.Int64Schema
            groupCount = schemas.Int64Schema
            __annotations__ = {
                "jobCount": jobCount,
                "personCount": personCount,
                "startingCount": startingCount,
                "departingCount": departingCount,
                "groupCount": groupCount,
            }
    
    startingCount: MetaOapg.properties.startingCount
    departingCount: MetaOapg.properties.departingCount
    jobCount: MetaOapg.properties.jobCount
    personCount: MetaOapg.properties.personCount
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobCount"]) -> MetaOapg.properties.jobCount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["personCount"]) -> MetaOapg.properties.personCount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["startingCount"]) -> MetaOapg.properties.startingCount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["departingCount"]) -> MetaOapg.properties.departingCount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["groupCount"]) -> MetaOapg.properties.groupCount: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["jobCount", "personCount", "startingCount", "departingCount", "groupCount", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobCount"]) -> MetaOapg.properties.jobCount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["personCount"]) -> MetaOapg.properties.personCount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["startingCount"]) -> MetaOapg.properties.startingCount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["departingCount"]) -> MetaOapg.properties.departingCount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["groupCount"]) -> typing.Union[MetaOapg.properties.groupCount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["jobCount", "personCount", "startingCount", "departingCount", "groupCount", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        startingCount: typing.Union[MetaOapg.properties.startingCount, decimal.Decimal, int, ],
        departingCount: typing.Union[MetaOapg.properties.departingCount, decimal.Decimal, int, ],
        jobCount: typing.Union[MetaOapg.properties.jobCount, decimal.Decimal, int, ],
        personCount: typing.Union[MetaOapg.properties.personCount, decimal.Decimal, int, ],
        groupCount: typing.Union[MetaOapg.properties.groupCount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'OrgCount':
        return super().__new__(
            cls,
            *args,
            startingCount=startingCount,
            departingCount=departingCount,
            jobCount=jobCount,
            personCount=personCount,
            groupCount=groupCount,
            _configuration=_configuration,
            **kwargs,
        )
