# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from chart_hop_python_sdk import schemas  # noqa: F401


class ScenarioCalculation(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "scenarioId",
            "allocated",
        }
        
        class properties:
            scenarioId = schemas.StrSchema
            allocated = schemas.DictSchema
            used = schemas.DictSchema
            __annotations__ = {
                "scenarioId": scenarioId,
                "allocated": allocated,
                "used": used,
            }
    
    scenarioId: MetaOapg.properties.scenarioId
    allocated: MetaOapg.properties.allocated
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scenarioId"]) -> MetaOapg.properties.scenarioId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["allocated"]) -> MetaOapg.properties.allocated: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["used"]) -> MetaOapg.properties.used: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["scenarioId", "allocated", "used", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scenarioId"]) -> MetaOapg.properties.scenarioId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["allocated"]) -> MetaOapg.properties.allocated: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["used"]) -> typing.Union[MetaOapg.properties.used, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["scenarioId", "allocated", "used", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        scenarioId: typing.Union[MetaOapg.properties.scenarioId, str, ],
        allocated: typing.Union[MetaOapg.properties.allocated, dict, frozendict.frozendict, ],
        used: typing.Union[MetaOapg.properties.used, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ScenarioCalculation':
        return super().__new__(
            cls,
            *args,
            scenarioId=scenarioId,
            allocated=allocated,
            used=used,
            _configuration=_configuration,
            **kwargs,
        )
