# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from chart_hop_python_sdk import schemas  # noqa: F401


class UpdateTaskConfig(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            description = schemas.StrSchema
            
            
            class type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "FORM_SUBMIT": "FORM_SUBMIT",
                        "CHANGE_APPROVE": "CHANGE_APPROVE",
                        "TIMEOFF_APPROVE": "TIMEOFF_APPROVE",
                        "SCENARIO_CHANGES_APPROVE": "SCENARIO_CHANGES_APPROVE",
                        "SCENARIO_CHANGES_CREATE": "SCENARIO_CHANGES_CREATE",
                        "ORG_IMPORT": "ORG_IMPORT",
                        "COMP_REVIEW_APPROVAL_SUBMIT": "COMP_REVIEW_APPROVAL_SUBMIT",
                        "SCENARIO_APPROVAL_SUBMIT": "SCENARIO_APPROVAL_SUBMIT",
                        "APPROVAL_CHAIN_UPDATE_FALLBACK_APPROVER": "APPROVAL_CHAIN_UPDATE_FALLBACK_APPROVER",
                        "ACTION": "ACTION",
                    }
                
                @schemas.classproperty
                def FORM_SUBMIT(cls):
                    return cls("FORM_SUBMIT")
                
                @schemas.classproperty
                def CHANGE_APPROVE(cls):
                    return cls("CHANGE_APPROVE")
                
                @schemas.classproperty
                def TIMEOFF_APPROVE(cls):
                    return cls("TIMEOFF_APPROVE")
                
                @schemas.classproperty
                def SCENARIO_CHANGES_APPROVE(cls):
                    return cls("SCENARIO_CHANGES_APPROVE")
                
                @schemas.classproperty
                def SCENARIO_CHANGES_CREATE(cls):
                    return cls("SCENARIO_CHANGES_CREATE")
                
                @schemas.classproperty
                def ORG_IMPORT(cls):
                    return cls("ORG_IMPORT")
                
                @schemas.classproperty
                def COMP_REVIEW_APPROVAL_SUBMIT(cls):
                    return cls("COMP_REVIEW_APPROVAL_SUBMIT")
                
                @schemas.classproperty
                def SCENARIO_APPROVAL_SUBMIT(cls):
                    return cls("SCENARIO_APPROVAL_SUBMIT")
                
                @schemas.classproperty
                def APPROVAL_CHAIN_UPDATE_FALLBACK_APPROVER(cls):
                    return cls("APPROVAL_CHAIN_UPDATE_FALLBACK_APPROVER")
                
                @schemas.classproperty
                def ACTION(cls):
                    return cls("ACTION")
        
            @staticmethod
            def dueDate() -> typing.Type['DueDate']:
                return DueDate
            
            
            class pastDueAction(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "NONE": "NONE",
                        "SET_EXPIRED": "SET_EXPIRED",
                    }
                
                @schemas.classproperty
                def NONE(cls):
                    return cls("NONE")
                
                @schemas.classproperty
                def SET_EXPIRED(cls):
                    return cls("SET_EXPIRED")
            isSkippable = schemas.BoolSchema
            label = schemas.StrSchema
            deleteId = schemas.StrSchema
            deleteAt = schemas.StrSchema
            __annotations__ = {
                "description": description,
                "type": type,
                "dueDate": dueDate,
                "pastDueAction": pastDueAction,
                "isSkippable": isSkippable,
                "label": label,
                "deleteId": deleteId,
                "deleteAt": deleteAt,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dueDate"]) -> 'DueDate': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pastDueAction"]) -> MetaOapg.properties.pastDueAction: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isSkippable"]) -> MetaOapg.properties.isSkippable: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["label"]) -> MetaOapg.properties.label: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deleteId"]) -> MetaOapg.properties.deleteId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deleteAt"]) -> MetaOapg.properties.deleteAt: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["description", "type", "dueDate", "pastDueAction", "isSkippable", "label", "deleteId", "deleteAt", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dueDate"]) -> typing.Union['DueDate', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pastDueAction"]) -> typing.Union[MetaOapg.properties.pastDueAction, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isSkippable"]) -> typing.Union[MetaOapg.properties.isSkippable, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["label"]) -> typing.Union[MetaOapg.properties.label, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deleteId"]) -> typing.Union[MetaOapg.properties.deleteId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deleteAt"]) -> typing.Union[MetaOapg.properties.deleteAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["description", "type", "dueDate", "pastDueAction", "isSkippable", "label", "deleteId", "deleteAt", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        dueDate: typing.Union['DueDate', schemas.Unset] = schemas.unset,
        pastDueAction: typing.Union[MetaOapg.properties.pastDueAction, str, schemas.Unset] = schemas.unset,
        isSkippable: typing.Union[MetaOapg.properties.isSkippable, bool, schemas.Unset] = schemas.unset,
        label: typing.Union[MetaOapg.properties.label, str, schemas.Unset] = schemas.unset,
        deleteId: typing.Union[MetaOapg.properties.deleteId, str, schemas.Unset] = schemas.unset,
        deleteAt: typing.Union[MetaOapg.properties.deleteAt, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UpdateTaskConfig':
        return super().__new__(
            cls,
            *args,
            description=description,
            type=type,
            dueDate=dueDate,
            pastDueAction=pastDueAction,
            isSkippable=isSkippable,
            label=label,
            deleteId=deleteId,
            deleteAt=deleteAt,
            _configuration=_configuration,
            **kwargs,
        )

from chart_hop_python_sdk.model.due_date import DueDate
