# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from chart_hop_python_sdk import schemas  # noqa: F401


class UpdateMessage(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            readAt = schemas.StrSchema
            seenAt = schemas.StrSchema
            __annotations__ = {
                "readAt": readAt,
                "seenAt": seenAt,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["readAt"]) -> MetaOapg.properties.readAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["seenAt"]) -> MetaOapg.properties.seenAt: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["readAt", "seenAt", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["readAt"]) -> typing.Union[MetaOapg.properties.readAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["seenAt"]) -> typing.Union[MetaOapg.properties.seenAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["readAt", "seenAt", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        readAt: typing.Union[MetaOapg.properties.readAt, str, schemas.Unset] = schemas.unset,
        seenAt: typing.Union[MetaOapg.properties.seenAt, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UpdateMessage':
        return super().__new__(
            cls,
            *args,
            readAt=readAt,
            seenAt=seenAt,
            _configuration=_configuration,
            **kwargs,
        )
