import typing_extensions

from chart_hop_python_sdk.paths import PathValues
from chart_hop_python_sdk.apis.paths.v1_org_org_id_access_entity_type import V1OrgOrgIdAccessEntityType
from chart_hop_python_sdk.apis.paths.v1_org_org_id_action_action_id import V1OrgOrgIdActionActionId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_action import V1OrgOrgIdAction
from chart_hop_python_sdk.apis.paths.v1_org_org_id_action_action_id_run import V1OrgOrgIdActionActionIdRun
from chart_hop_python_sdk.apis.paths.v1_org_org_id_ai_form_response_summary import V1OrgOrgIdAiFormResponseSummary
from chart_hop_python_sdk.apis.paths.v1_app_config_app_id import V1AppConfigAppId
from chart_hop_python_sdk.apis.paths.v1_app_config_app_id_user_id import V1AppConfigAppIdUserId
from chart_hop_python_sdk.apis.paths.v1_app_config import V1AppConfig
from chart_hop_python_sdk.apis.paths.v1_app_notify import V1AppNotify
from chart_hop_python_sdk.apis.paths.v1_app_app_id import V1AppAppId
from chart_hop_python_sdk.apis.paths.v1_app_org_org_id_install_app_user_id_token import V1AppOrgOrgIdInstallAppUserIdToken
from chart_hop_python_sdk.apis.paths.v1_app_org_org_id_install_app_user_id_code import V1AppOrgOrgIdInstallAppUserIdCode
from chart_hop_python_sdk.apis.paths.v1_app import V1App
from chart_hop_python_sdk.apis.paths.v1_app_org_org_id import V1AppOrgOrgId
from chart_hop_python_sdk.apis.paths.v1_app_org_org_id_install_app_user_id_run import V1AppOrgOrgIdInstallAppUserIdRun
from chart_hop_python_sdk.apis.paths.v1_app_org_org_id_install_app_user_id import V1AppOrgOrgIdInstallAppUserId
from chart_hop_python_sdk.apis.paths.v1_app_name_app_name import V1AppNameAppName
from chart_hop_python_sdk.apis.paths.v1_app_org_org_id_install_name_app_name import V1AppOrgOrgIdInstallNameAppName
from chart_hop_python_sdk.apis.paths.v1_app_org_org_id_install import V1AppOrgOrgIdInstall
from chart_hop_python_sdk.apis.paths.v1_app_org_org_id_install_validate import V1AppOrgOrgIdInstallValidate
from chart_hop_python_sdk.apis.paths.v1_app_org_org_id_install_app_user_id_installdata_install_data_name import V1AppOrgOrgIdInstallAppUserIdInstalldataInstallDataName
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_request_approval_request_id_scenario_response import V1OrgOrgIdApprovalRequestApprovalRequestIdScenarioResponse
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_request_scenario_job_job_id import V1OrgOrgIdApprovalRequestScenarioJobJobId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_request_entity_scenario import V1OrgOrgIdApprovalRequestEntityScenario
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_chain import V1OrgOrgIdApprovalChain
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_chain_approval_chain_id import V1OrgOrgIdApprovalChainApprovalChainId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_chain_approval_chain_id_request_approval_request_id import V1OrgOrgIdApprovalChainApprovalChainIdRequestApprovalRequestId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_chain_approval_chain_id_request_entity_comp_review import V1OrgOrgIdApprovalChainApprovalChainIdRequestEntityCompReview
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_chain_approval_chain_id_stage import V1OrgOrgIdApprovalChainApprovalChainIdStage
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_chain_approval_chain_id_stage_approval_chain_stage_id import V1OrgOrgIdApprovalChainApprovalChainIdStageApprovalChainStageId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_chain_create_default_chain import V1OrgOrgIdApprovalChainCreateDefaultChain
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_chain_approval_chain_id_request import V1OrgOrgIdApprovalChainApprovalChainIdRequest
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_chain_approval_chain_id_request_entity_scenario import V1OrgOrgIdApprovalChainApprovalChainIdRequestEntityScenario
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_chain_approval_chain_id_request_approval_request_id_reassign_approver import V1OrgOrgIdApprovalChainApprovalChainIdRequestApprovalRequestIdReassignApprover
from chart_hop_python_sdk.apis.paths.v1_org_org_id_approval_chain_approval_chain_id_request_approval_request_id_send_reminder import V1OrgOrgIdApprovalChainApprovalChainIdRequestApprovalRequestIdSendReminder
from chart_hop_python_sdk.apis.paths.v1_org_org_id_assessment_bulk_duplicate import V1OrgOrgIdAssessmentBulkDuplicate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_assessment_bulk_move import V1OrgOrgIdAssessmentBulkMove
from chart_hop_python_sdk.apis.paths.v1_org_org_id_assessment_bulk_delete import V1OrgOrgIdAssessmentBulkDelete
from chart_hop_python_sdk.apis.paths.v1_org_org_id_assessment_assessment_id import V1OrgOrgIdAssessmentAssessmentId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_assessment_assessment_id_complete import V1OrgOrgIdAssessmentAssessmentIdComplete
from chart_hop_python_sdk.apis.paths.v1_org_org_id_assessment_assessment_id_reactivate import V1OrgOrgIdAssessmentAssessmentIdReactivate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_assessment_assessment_id_form_form_id_expire import V1OrgOrgIdAssessmentAssessmentIdFormFormIdExpire
from chart_hop_python_sdk.apis.paths.v1_org_org_id_assessment import V1OrgOrgIdAssessment
from chart_hop_python_sdk.apis.paths.v1_customer_customer_id_billing_cancel import V1CustomerCustomerIdBillingCancel
from chart_hop_python_sdk.apis.paths.v1_customer_customer_id_billing_checkout import V1CustomerCustomerIdBillingCheckout
from chart_hop_python_sdk.apis.paths.v1_customer_customer_id_billing import V1CustomerCustomerIdBilling
from chart_hop_python_sdk.apis.paths.v1_org_org_id_budget_pool_id_guidelines import V1OrgOrgIdBudgetPoolIdGuidelines
from chart_hop_python_sdk.apis.paths.v1_org_org_id_budget_pool_id_calculate import V1OrgOrgIdBudgetPoolIdCalculate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_budget_pool import V1OrgOrgIdBudgetPool
from chart_hop_python_sdk.apis.paths.v1_org_org_id_budget_pool_id import V1OrgOrgIdBudgetPoolId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_budget_pool_id_preview import V1OrgOrgIdBudgetPoolIdPreview
from chart_hop_python_sdk.apis.paths.v1_org_org_id_calendar import V1OrgOrgIdCalendar
from chart_hop_python_sdk.apis.paths.v1_org_org_id_category import V1OrgOrgIdCategory
from chart_hop_python_sdk.apis.paths.v1_org_org_id_category_category_id import V1OrgOrgIdCategoryCategoryId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_category_sort_upsert import V1OrgOrgIdCategorySortUpsert
from chart_hop_python_sdk.apis.paths.v1_org_org_id_category_sort import V1OrgOrgIdCategorySort
from chart_hop_python_sdk.apis.paths.v1_org_org_id_change_bulkupdate import V1OrgOrgIdChangeBulkupdate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_change_type_validate import V1OrgOrgIdChangeTypeValidate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_change_type import V1OrgOrgIdChangeType
from chart_hop_python_sdk.apis.paths.v1_org_org_id_change_change_id import V1OrgOrgIdChangeChangeId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_change import V1OrgOrgIdChange
from chart_hop_python_sdk.apis.paths.v1_org_org_id_change_change_id_approver import V1OrgOrgIdChangeChangeIdApprover
from chart_hop_python_sdk.apis.paths.v1_org_org_id_change_scenario_scenario_id import V1OrgOrgIdChangeScenarioScenarioId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_change_sync_type import V1OrgOrgIdChangeSyncType
from chart_hop_python_sdk.apis.paths.v1_org_org_id_change_depart_rehire import V1OrgOrgIdChangeDepartRehire
from chart_hop_python_sdk.apis.paths.v1_org_org_id_change_bulkchange import V1OrgOrgIdChangeBulkchange
from chart_hop_python_sdk.apis.paths.v1_org_org_id_change_change_id_approve import V1OrgOrgIdChangeChangeIdApprove
from chart_hop_python_sdk.apis.paths.v1_org_org_id_scenario_scenario_id_change_change_id import V1OrgOrgIdScenarioScenarioIdChangeChangeId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_scenario_scenario_id_change_change_id_status_process_id import V1OrgOrgIdScenarioScenarioIdChangeChangeIdStatusProcessId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comment_comment_id import V1OrgOrgIdCommentCommentId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comment import V1OrgOrgIdComment
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comment_entity_entity_id import V1OrgOrgIdCommentEntityEntityId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comment_comp_review_comp_review_id import V1OrgOrgIdCommentCompReviewCompReviewId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comment_scenario_scenario_id import V1OrgOrgIdCommentScenarioScenarioId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_band_band_id import V1OrgOrgIdBandBandId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_band import V1OrgOrgIdBand
from chart_hop_python_sdk.apis.paths.v1_org_org_id_band_reset import V1OrgOrgIdBandReset
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_bulk_delete import V1OrgOrgIdCompReviewBulkDelete
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_bulk_duplicate import V1OrgOrgIdCompReviewBulkDuplicate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_duplicate import V1OrgOrgIdCompReviewCompReviewIdDuplicate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id import V1OrgOrgIdCompReviewCompReviewId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_pause import V1OrgOrgIdCompReviewCompReviewIdPause
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_conclude import V1OrgOrgIdCompReviewCompReviewIdConclude
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_preview import V1OrgOrgIdCompReviewCompReviewIdPreview
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_in_cycle import V1OrgOrgIdCompReviewCompReviewIdInCycle
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review import V1OrgOrgIdCompReview
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_metadata import V1OrgOrgIdCompReviewCompReviewIdMetadata
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_generate import V1OrgOrgIdCompReviewCompReviewIdGenerate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_in_cycle_changes import V1OrgOrgIdCompReviewCompReviewIdInCycleChanges
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_in_cycle_changes_change_id import V1OrgOrgIdCompReviewCompReviewIdInCycleChangesChangeId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_in_cycle_collabicient import V1OrgOrgIdCompReviewCompReviewIdInCycleCollabicient
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_eligible_employees import V1OrgOrgIdCompReviewCompReviewIdEligibleEmployees
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_associated_entities import V1OrgOrgIdCompReviewCompReviewIdAssociatedEntities
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_send_reminder_email import V1OrgOrgIdCompReviewCompReviewIdSendReminderEmail
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_approval_requests import V1OrgOrgIdCompReviewCompReviewIdApprovalRequests
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_approval_requests_approval_request_id import V1OrgOrgIdCompReviewCompReviewIdApprovalRequestsApprovalRequestId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_export import V1OrgOrgIdCompReviewCompReviewIdExport
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_export_audit import V1OrgOrgIdCompReviewCompReviewIdExportAudit
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_export_comments import V1OrgOrgIdCompReviewCompReviewIdExportComments
from chart_hop_python_sdk.apis.paths.v1_org_org_id_comp_review_comp_review_id_visualizations import V1OrgOrgIdCompReviewCompReviewIdVisualizations
from chart_hop_python_sdk.apis.paths.v1_org_org_id_content_content_id import V1OrgOrgIdContentContentId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_content_homepage_render import V1OrgOrgIdContentHomepageRender
from chart_hop_python_sdk.apis.paths.v1_org_org_id_content_homepage import V1OrgOrgIdContentHomepage
from chart_hop_python_sdk.apis.paths.v1_org_org_id_content import V1OrgOrgIdContent
from chart_hop_python_sdk.apis.paths.v1_org_org_id_content_path_path import V1OrgOrgIdContentPathPath
from chart_hop_python_sdk.apis.paths.v1_org_org_id_content_path_path_render import V1OrgOrgIdContentPathPathRender
from chart_hop_python_sdk.apis.paths.v1_customer_customer_id_subscription import V1CustomerCustomerIdSubscription
from chart_hop_python_sdk.apis.paths.v1_customer_customer_id import V1CustomerCustomerId
from chart_hop_python_sdk.apis.paths.v1_customer import V1Customer
from chart_hop_python_sdk.apis.paths.v1_customer_customer_id_invoices import V1CustomerCustomerIdInvoices
from chart_hop_python_sdk.apis.paths.v1_org_org_id_data_view import V1OrgOrgIdDataView
from chart_hop_python_sdk.apis.paths.v1_org_org_id_data_view_data_view_id import V1OrgOrgIdDataViewDataViewId
from chart_hop_python_sdk.apis.paths.v1_email_template import V1EmailTemplate
from chart_hop_python_sdk.apis.paths.v1_email_template_email_template_id import V1EmailTemplateEmailTemplateId
from chart_hop_python_sdk.apis.paths.v1_email_template_essential import V1EmailTemplateEssential
from chart_hop_python_sdk.apis.paths.v1_email_template_non_essential import V1EmailTemplateNonEssential
from chart_hop_python_sdk.apis.paths.v1_email_template_name_name import V1EmailTemplateNameName
from chart_hop_python_sdk.apis.paths.v1_org_org_id_event_event_id import V1OrgOrgIdEventEventId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_event import V1OrgOrgIdEvent
from chart_hop_python_sdk.apis.paths.v1_org_org_id_event_event_id_notify import V1OrgOrgIdEventEventIdNotify
from chart_hop_python_sdk.apis.paths.v1_org_org_id_event_notify_inbound_app_id_inbound_id import V1OrgOrgIdEventNotifyInboundAppIdInboundId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_event_notify_outbound_app_app_id import V1OrgOrgIdEventNotifyOutboundAppAppId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_exchange_rate_date_history import V1OrgOrgIdExchangeRateDateHistory
from chart_hop_python_sdk.apis.paths.v1_org_org_id_exchange_rate_date_custom_bulkupdate import V1OrgOrgIdExchangeRateDateCustomBulkupdate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_exchange_rate_date import V1OrgOrgIdExchangeRateDate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_exchange_rate_date_global import V1OrgOrgIdExchangeRateDateGlobal
from chart_hop_python_sdk.apis.paths.v1_org_org_id_exchange_rate_date_custom import V1OrgOrgIdExchangeRateDateCustom
from chart_hop_python_sdk.apis.paths.v1_org_org_id_export_powerpoint_report_report_id import V1OrgOrgIdExportPowerpointReportReportId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_export_csv_scenario_scenario_id_comments import V1OrgOrgIdExportCsvScenarioScenarioIdComments
from chart_hop_python_sdk.apis.paths.v1_org_org_id_export_powerpoint_org import V1OrgOrgIdExportPowerpointOrg
from chart_hop_python_sdk.apis.paths.v1_org_org_id_export_csv_change import V1OrgOrgIdExportCsvChange
from chart_hop_python_sdk.apis.paths.v1_org_org_id_export_csv_users import V1OrgOrgIdExportCsvUsers
from chart_hop_python_sdk.apis.paths.v1_org_org_id_export_csv_task_review_id import V1OrgOrgIdExportCsvTaskReviewId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_export_csv_scenario_scenario_id import V1OrgOrgIdExportCsvScenarioScenarioId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_export_pdf_review_assessment_id import V1OrgOrgIdExportPdfReviewAssessmentId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_export_zip_file import V1OrgOrgIdExportZipFile
from chart_hop_python_sdk.apis.paths.v1_org_org_id_export_csv_fields import V1OrgOrgIdExportCsvFields
from chart_hop_python_sdk.apis.paths.v1_org_org_id_export_csv_snapshot import V1OrgOrgIdExportCsvSnapshot
from chart_hop_python_sdk.apis.paths.v1_org_org_id_cql_validate import V1OrgOrgIdCqlValidate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_cql_evaluate import V1OrgOrgIdCqlEvaluate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_field import V1OrgOrgIdField
from chart_hop_python_sdk.apis.paths.v1_org_org_id_field_field_id import V1OrgOrgIdFieldFieldId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_field_remove_overrides import V1OrgOrgIdFieldRemoveOverrides
from chart_hop_python_sdk.apis.paths.v1_org_org_id_field_remove_category import V1OrgOrgIdFieldRemoveCategory
from chart_hop_python_sdk.apis.paths.v1_org_org_id_field_field_id_dryrun import V1OrgOrgIdFieldFieldIdDryrun
from chart_hop_python_sdk.apis.paths.v1_org_org_id_field_delete import V1OrgOrgIdFieldDelete
from chart_hop_python_sdk.apis.paths.v1_org_org_id_field_built_in import V1OrgOrgIdFieldBuiltIn
from chart_hop_python_sdk.apis.paths.v1_org_org_id_field_category_category_id import V1OrgOrgIdFieldCategoryCategoryId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_field_category import V1OrgOrgIdFieldCategory
from chart_hop_python_sdk.apis.paths.v1_org_org_id_field_status import V1OrgOrgIdFieldStatus
from chart_hop_python_sdk.apis.paths.v1_org_org_id_file import V1OrgOrgIdFile
from chart_hop_python_sdk.apis.paths.v1_org_org_id_file_file_id import V1OrgOrgIdFileFileId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_file_file_id_download import V1OrgOrgIdFileFileIdDownload
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_form_id import V1OrgOrgIdFormFormId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_delete import V1OrgOrgIdFormDelete
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_form_id_draft import V1OrgOrgIdFormFormIdDraft
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_form_id_submit_draft import V1OrgOrgIdFormFormIdSubmitDraft
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_form_id_submit import V1OrgOrgIdFormFormIdSubmit
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_available import V1OrgOrgIdFormAvailable
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_form_id_render import V1OrgOrgIdFormFormIdRender
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_form_id_rerender_question_update_question_id import V1OrgOrgIdFormFormIdRerenderQuestionUpdateQuestionId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_draft_draft_id import V1OrgOrgIdFormDraftDraftId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form import V1OrgOrgIdForm
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_person_person_id import V1OrgOrgIdFormPersonPersonId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_form_id_collect import V1OrgOrgIdFormFormIdCollect
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_form_id_remind import V1OrgOrgIdFormFormIdRemind
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_status import V1OrgOrgIdFormStatus
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_response_form_response_id import V1OrgOrgIdFormResponseFormResponseId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_response import V1OrgOrgIdFormResponse
from chart_hop_python_sdk.apis.paths.v1_org_org_id_form_response_count import V1OrgOrgIdFormResponseCount
from chart_hop_python_sdk.apis.paths.v1_media import V1Media
from chart_hop_python_sdk.apis.paths.v1_media_media_id import V1MediaMediaId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_guideline import V1OrgOrgIdGuideline
from chart_hop_python_sdk.apis.paths.v1_org_org_id_guideline_id import V1OrgOrgIdGuidelineId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_guideline_id_calculate import V1OrgOrgIdGuidelineIdCalculate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_import_csv_data import V1OrgOrgIdImportCsvData
from chart_hop_python_sdk.apis.paths.v1_org_org_id_import_csv_column_match import V1OrgOrgIdImportCsvColumnMatch
from chart_hop_python_sdk.apis.paths.v1_org_org_id_import_csv_filepath import V1OrgOrgIdImportCsvFilepath
from chart_hop_python_sdk.apis.paths.v1_org_org_id_import_spreadsheet_validate_format import V1OrgOrgIdImportSpreadsheetValidateFormat
from chart_hop_python_sdk.apis.paths.v1_org_org_id_import_csv_initial_column_match import V1OrgOrgIdImportCsvInitialColumnMatch
from chart_hop_python_sdk.apis.paths.v1_org_org_id_job_level import V1OrgOrgIdJobLevel
from chart_hop_python_sdk.apis.paths.v1_org_org_id_job_level_job_level_id import V1OrgOrgIdJobLevelJobLevelId
from chart_hop_python_sdk.apis.paths.v1_legaldoc_name import V1LegaldocName
from chart_hop_python_sdk.apis.paths.v1_legaldoc import V1Legaldoc
from chart_hop_python_sdk.apis.paths.v1_org_org_id_media import V1OrgOrgIdMedia
from chart_hop_python_sdk.apis.paths.v1_org_org_id_media_media_id import V1OrgOrgIdMediaMediaId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_message_message_id import V1OrgOrgIdMessageMessageId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_message_me import V1OrgOrgIdMessageMe
from chart_hop_python_sdk.apis.paths.v1_org_org_id_message import V1OrgOrgIdMessage
from chart_hop_python_sdk.apis.paths.v1_org_org_id_message_me_message_key import V1OrgOrgIdMessageMeMessageKey
from chart_hop_python_sdk.apis.paths.v1_org_org_id_message_message_id_read import V1OrgOrgIdMessageMessageIdRead
from chart_hop_python_sdk.apis.paths.v1_org_org_id_message_bulk_read import V1OrgOrgIdMessageBulkRead
from chart_hop_python_sdk.apis.paths.v1_org_org_id_message_bulk_seen import V1OrgOrgIdMessageBulkSeen
from chart_hop_python_sdk.apis.paths.v1_org_org_id_metric import V1OrgOrgIdMetric
from chart_hop_python_sdk.apis.paths.v1_org_org_id_multiplier_multiplier_id import V1OrgOrgIdMultiplierMultiplierId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_multiplier import V1OrgOrgIdMultiplier
from chart_hop_python_sdk.apis.paths.v1_org_org_id_notification import V1OrgOrgIdNotification
from chart_hop_python_sdk.apis.paths.oauth_token import OauthToken
from chart_hop_python_sdk.apis.paths.oauth_app_app_name import OauthAppAppName
from chart_hop_python_sdk.apis.paths.oauth_sso_idp_login import OauthSsoIdpLogin
from chart_hop_python_sdk.apis.paths.oauth_sso_idp_access_token import OauthSsoIdpAccessToken
from chart_hop_python_sdk.apis.paths.oauth_token_view import OauthTokenView
from chart_hop_python_sdk.apis.paths.oauth_token_sso_type import OauthTokenSsoType
from chart_hop_python_sdk.apis.paths.v1_org_org_id_onboard import V1OrgOrgIdOnboard
from chart_hop_python_sdk.apis.paths.v1_org_org_id_onboard_step_name_skip import V1OrgOrgIdOnboardStepNameSkip
from chart_hop_python_sdk.apis.paths.v1_org_org_id_config import V1OrgOrgIdConfig
from chart_hop_python_sdk.apis.paths.v1_org import V1Org
from chart_hop_python_sdk.apis.paths.v1_org_org_id import V1OrgOrgId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_data_users_persons import V1OrgOrgIdDataUsersPersons
from chart_hop_python_sdk.apis.paths.v1_org_org_id_change_head import V1OrgOrgIdChangeHead
from chart_hop_python_sdk.apis.paths.v1_org_org_id_welcome_email import V1OrgOrgIdWelcomeEmail
from chart_hop_python_sdk.apis.paths.v1_org_org_id_test_email import V1OrgOrgIdTestEmail
from chart_hop_python_sdk.apis.paths.v1_org_org_id_agreement import V1OrgOrgIdAgreement
from chart_hop_python_sdk.apis.paths.v1_org_org_id_access import V1OrgOrgIdAccess
from chart_hop_python_sdk.apis.paths.v1_org_org_id_data_user_person_count import V1OrgOrgIdDataUserPersonCount
from chart_hop_python_sdk.apis.paths.v1_org_org_id_data_user_person import V1OrgOrgIdDataUserPerson
from chart_hop_python_sdk.apis.paths.v1_org_org_app_install_code import V1OrgOrgAppInstallCode
from chart_hop_python_sdk.apis.paths.v1_org_app_install_code_validate import V1OrgAppInstallCodeValidate
from chart_hop_python_sdk.apis.paths.org_slug import OrgSlug
from chart_hop_python_sdk.apis.paths.v1_org_slug_slug import V1OrgSlugSlug
from chart_hop_python_sdk.apis.paths.v1_org_org_id_policy_policy_id import V1OrgOrgIdPolicyPolicyId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_policy import V1OrgOrgIdPolicy
from chart_hop_python_sdk.apis.paths.v1_org_org_id_policy_policy_id_copy import V1OrgOrgIdPolicyPolicyIdCopy
from chart_hop_python_sdk.apis.paths.v1_org_org_id_policy_validate import V1OrgOrgIdPolicyValidate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_policy_action import V1OrgOrgIdPolicyAction
from chart_hop_python_sdk.apis.paths.v1_org_org_id_preload import V1OrgOrgIdPreload
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process_process_id_decrement import V1OrgOrgIdProcessProcessIdDecrement
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process_process_id_increment import V1OrgOrgIdProcessProcessIdIncrement
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process_process_id_resume import V1OrgOrgIdProcessProcessIdResume
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process import V1OrgOrgIdProcess
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process_self_serve import V1OrgOrgIdProcessSelfServe
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process_process_id_state import V1OrgOrgIdProcessProcessIdState
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process_process_id_resume_with_file import V1OrgOrgIdProcessProcessIdResumeWithFile
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process_process_id_events import V1OrgOrgIdProcessProcessIdEvents
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process_process_id_file import V1OrgOrgIdProcessProcessIdFile
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process_process_id_log import V1OrgOrgIdProcessProcessIdLog
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process_process_id import V1OrgOrgIdProcessProcessId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process_last_sync_app_user_id import V1OrgOrgIdProcessLastSyncAppUserId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_process_create_id_override import V1OrgOrgIdProcessCreateIdOverride
from chart_hop_python_sdk.apis.paths.v1_product_product_id import V1ProductProductId
from chart_hop_python_sdk.apis.paths.v1_product import V1Product
from chart_hop_python_sdk.apis.paths.v1_org_org_id_profile_tab_job_job_id_profile_tab_tab_id import V1OrgOrgIdProfileTabJobJobIdProfileTabTabId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_profile_tab_profile_tab_id import V1OrgOrgIdProfileTabProfileTabId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_profile_tab import V1OrgOrgIdProfileTab
from chart_hop_python_sdk.apis.paths.v1_org_org_id_profile_tab_person_person_id import V1OrgOrgIdProfileTabPersonPersonId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_profile_tab_job_job_id import V1OrgOrgIdProfileTabJobJobId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_query_query_token import V1OrgOrgIdQueryQueryToken
from chart_hop_python_sdk.apis.paths.v1_org_org_id_query import V1OrgOrgIdQuery
from chart_hop_python_sdk.apis.paths.v1_org_org_id_question_question_id import V1OrgOrgIdQuestionQuestionId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_question import V1OrgOrgIdQuestion
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_report_id_chart import V1OrgOrgIdReportReportIdChart
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_chart_chart_id import V1OrgOrgIdReportChartChartId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_report_id_chart_chart_id_clone import V1OrgOrgIdReportReportIdChartChartIdClone
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_report_id_chart_chart_id_data import V1OrgOrgIdReportReportIdChartChartIdData
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_report_id_chart_chart_id_query import V1OrgOrgIdReportReportIdChartChartIdQuery
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report import V1OrgOrgIdReport
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_count import V1OrgOrgIdReportCount
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_report_id import V1OrgOrgIdReportReportId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_query import V1OrgOrgIdReportQuery
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_report_id_query import V1OrgOrgIdReportReportIdQuery
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_report_id_chart_chart_id_export_csv import V1OrgOrgIdReportReportIdChartChartIdExportCsv
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_report_id_clone import V1OrgOrgIdReportReportIdClone
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_bulk_delete import V1OrgOrgIdReportBulkDelete
from chart_hop_python_sdk.apis.paths.v1_org_org_id_report_bulk_duplicate import V1OrgOrgIdReportBulkDuplicate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_role import V1OrgOrgIdRole
from chart_hop_python_sdk.apis.paths.v1_org_org_id_role_role_id import V1OrgOrgIdRoleRoleId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_role_role_id_copy import V1OrgOrgIdRoleRoleIdCopy
from chart_hop_python_sdk.apis.paths.saml_org_login import SamlOrgLogin
from chart_hop_python_sdk.apis.paths.saml_sso_org import SamlSsoOrg
from chart_hop_python_sdk.apis.paths.saml_org_org_id_xml_cert import SamlOrgOrgIdXmlCert
from chart_hop_python_sdk.apis.paths.v1_org_org_id_scenario_bulk_archive import V1OrgOrgIdScenarioBulkArchive
from chart_hop_python_sdk.apis.paths.v1_org_org_id_scenario_bulk_delete import V1OrgOrgIdScenarioBulkDelete
from chart_hop_python_sdk.apis.paths.v1_org_org_id_scenario_bulk_unarchive import V1OrgOrgIdScenarioBulkUnarchive
from chart_hop_python_sdk.apis.paths.v1_org_org_id_scenario_scenario_id import V1OrgOrgIdScenarioScenarioId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_scenario import V1OrgOrgIdScenario
from chart_hop_python_sdk.apis.paths.v1_org_org_id_scenario_scenario_id_dates import V1OrgOrgIdScenarioScenarioIdDates
from chart_hop_python_sdk.apis.paths.v1_org_org_id_scenario_scenario_id_merge import V1OrgOrgIdScenarioScenarioIdMerge
from chart_hop_python_sdk.apis.paths.v1_org_org_id_scenario_scenario_id_combine import V1OrgOrgIdScenarioScenarioIdCombine
from chart_hop_python_sdk.apis.paths.v1_org_org_id_scenario_scenario_id_recalculate_metadata import V1OrgOrgIdScenarioScenarioIdRecalculateMetadata
from chart_hop_python_sdk.apis.paths.v1_org_org_id_scenario_scenario_id_update_shared_view import V1OrgOrgIdScenarioScenarioIdUpdateSharedView
from chart_hop_python_sdk.apis.paths.v1_org_org_id_search import V1OrgOrgIdSearch
from chart_hop_python_sdk.apis.paths.v1_status import V1Status
from chart_hop_python_sdk.apis.paths.v1_stock import V1Stock
from chart_hop_python_sdk.apis.paths.v1_stock_id import V1StockId
from chart_hop_python_sdk.apis.paths.v1_stock_symbol_date_type import V1StockSymbolDateType
from chart_hop_python_sdk.apis.paths.v1_stripe_setup_intent import V1StripeSetupIntent
from chart_hop_python_sdk.apis.paths.v1_stripe_plan import V1StripePlan
from chart_hop_python_sdk.apis.paths.v1_stripe_webhook import V1StripeWebhook
from chart_hop_python_sdk.apis.paths.v1_stripe_product_product_id import V1StripeProductProductId
from chart_hop_python_sdk.apis.paths.v1_stripe_product import V1StripeProduct
from chart_hop_python_sdk.apis.paths.v1_org_org_id_table_table_id import V1OrgOrgIdTableTableId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_table_table_id_import import V1OrgOrgIdTableTableIdImport
from chart_hop_python_sdk.apis.paths.v1_org_org_id_table import V1OrgOrgIdTable
from chart_hop_python_sdk.apis.paths.v1_org_org_id_table_table_id_data import V1OrgOrgIdTableTableIdData
from chart_hop_python_sdk.apis.paths.v1_org_org_id_table_table_id_data_key_column_key_value import V1OrgOrgIdTableTableIdDataKeyColumnKeyValue
from chart_hop_python_sdk.apis.paths.v1_org_org_id_table_table_id_data_key_column_key_value_purge import V1OrgOrgIdTableTableIdDataKeyColumnKeyValuePurge
from chart_hop_python_sdk.apis.paths.v1_org_org_id_table_table_id_export import V1OrgOrgIdTableTableIdExport
from chart_hop_python_sdk.apis.paths.v1_org_org_id_task_config import V1OrgOrgIdTaskConfig
from chart_hop_python_sdk.apis.paths.v1_org_org_id_task_config_id import V1OrgOrgIdTaskConfigId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_task_task_id_mark_done import V1OrgOrgIdTaskTaskIdMarkDone
from chart_hop_python_sdk.apis.paths.v1_org_org_id_task_task_id_skip import V1OrgOrgIdTaskTaskIdSkip
from chart_hop_python_sdk.apis.paths.v1_org_org_id_task import V1OrgOrgIdTask
from chart_hop_python_sdk.apis.paths.v1_org_org_id_task_task import V1OrgOrgIdTaskTask
from chart_hop_python_sdk.apis.paths.v1_org_org_id_task_me import V1OrgOrgIdTaskMe
from chart_hop_python_sdk.apis.paths.v1_org_org_id_task_remind import V1OrgOrgIdTaskRemind
from chart_hop_python_sdk.apis.paths.v1_org_org_id_task_task_id import V1OrgOrgIdTaskTaskId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_task_bulk_delete import V1OrgOrgIdTaskBulkDelete
from chart_hop_python_sdk.apis.paths.v1_org_org_id_task_assessment_id_form_id import V1OrgOrgIdTaskAssessmentIdFormId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_task_summary_assessment_id import V1OrgOrgIdTaskSummaryAssessmentId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_template_bulk_delete import V1OrgOrgIdTemplateBulkDelete
from chart_hop_python_sdk.apis.paths.v1_org_org_id_template_bulk_duplicate import V1OrgOrgIdTemplateBulkDuplicate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_template_template_id import V1OrgOrgIdTemplateTemplateId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_template import V1OrgOrgIdTemplate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_template_template_id_render import V1OrgOrgIdTemplateTemplateIdRender
from chart_hop_python_sdk.apis.paths.v1_org_org_id_template_template_id_preview import V1OrgOrgIdTemplateTemplateIdPreview
from chart_hop_python_sdk.apis.paths.v1_org_org_id_template_template_id_generate import V1OrgOrgIdTemplateTemplateIdGenerate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_template_email_template_name import V1OrgOrgIdTemplateEmailTemplateName
from chart_hop_python_sdk.apis.paths.v1_org_org_id_template_email import V1OrgOrgIdTemplateEmail
from chart_hop_python_sdk.apis.paths.v1_org_org_id_timeoff_request_validate import V1OrgOrgIdTimeoffRequestValidate
from chart_hop_python_sdk.apis.paths.v1_org_org_id_timeoff import V1OrgOrgIdTimeoff
from chart_hop_python_sdk.apis.paths.v1_org_org_id_timeoff_time_off_id import V1OrgOrgIdTimeoffTimeOffId
from chart_hop_python_sdk.apis.paths.v1_org_org_id_timeoff_request import V1OrgOrgIdTimeoffRequest
from chart_hop_python_sdk.apis.paths.v1_org_org_id_timeoff_time_off_id_approve import V1OrgOrgIdTimeoffTimeOffIdApprove
from chart_hop_python_sdk.apis.paths.v1_org_org_id_timeoff_time_off_id_reject import V1OrgOrgIdTimeoffTimeOffIdReject
from chart_hop_python_sdk.apis.paths.v1_org_org_id_usage_type import V1OrgOrgIdUsageType
from chart_hop_python_sdk.apis.paths.v1_user_user_id import V1UserUserId
from chart_hop_python_sdk.apis.paths.v1_user import V1User
from chart_hop_python_sdk.apis.paths.v1_user_user_id_token import V1UserUserIdToken
from chart_hop_python_sdk.apis.paths.v1_user_token import V1UserToken
from chart_hop_python_sdk.apis.paths.v1_user_assign import V1UserAssign
from chart_hop_python_sdk.apis.paths.v1_user_me import V1UserMe
from chart_hop_python_sdk.apis.paths.v1_user_me_view import V1UserMeView
from chart_hop_python_sdk.apis.paths.v1_user_email_email import V1UserEmailEmail
from chart_hop_python_sdk.apis.paths.v1_user_person_person_id import V1UserPersonPersonId
from chart_hop_python_sdk.apis.paths.v1_user_invite import V1UserInvite
from chart_hop_python_sdk.apis.paths.v1_user_user_id_password import V1UserUserIdPassword
from chart_hop_python_sdk.apis.paths.v1_user_sendreset import V1UserSendreset
from chart_hop_python_sdk.apis.paths.v1_webauthn_register import V1WebauthnRegister
from chart_hop_python_sdk.apis.paths.v1_webauthn_register_email_base64 import V1WebauthnRegisterEmailBase64
from chart_hop_python_sdk.apis.paths.v1_webauthn_verify import V1WebauthnVerify
from chart_hop_python_sdk.apis.paths.v2_org_org_id_change_change_id import V2OrgOrgIdChangeChangeId
from chart_hop_python_sdk.apis.paths.v2_org_org_id_change import V2OrgOrgIdChange
from chart_hop_python_sdk.apis.paths.v2_org_org_id_group_type import V2OrgOrgIdGroupType
from chart_hop_python_sdk.apis.paths.v2_org_org_id_group_type_group_id import V2OrgOrgIdGroupTypeGroupId
from chart_hop_python_sdk.apis.paths.v2_org_org_id_group_count import V2OrgOrgIdGroupCount
from chart_hop_python_sdk.apis.paths.v2_org_org_id_group_type_bulk_delete import V2OrgOrgIdGroupTypeBulkDelete
from chart_hop_python_sdk.apis.paths.v2_org_org_id_group_type_import import V2OrgOrgIdGroupTypeImport
from chart_hop_python_sdk.apis.paths.v2_org_org_id_group_graph import V2OrgOrgIdGroupGraph
from chart_hop_python_sdk.apis.paths.v2_org_org_id_group_orphaned import V2OrgOrgIdGroupOrphaned
from chart_hop_python_sdk.apis.paths.v2_org_org_id_job_job_id import V2OrgOrgIdJobJobId
from chart_hop_python_sdk.apis.paths.v2_org_org_id_job_count import V2OrgOrgIdJobCount
from chart_hop_python_sdk.apis.paths.v2_org_org_id_job_bulkupdate import V2OrgOrgIdJobBulkupdate
from chart_hop_python_sdk.apis.paths.v2_org_org_id_job_graph import V2OrgOrgIdJobGraph
from chart_hop_python_sdk.apis.paths.v2_org_org_id_job_graph_counts import V2OrgOrgIdJobGraphCounts
from chart_hop_python_sdk.apis.paths.v2_org_org_id_job import V2OrgOrgIdJob
from chart_hop_python_sdk.apis.paths.v2_org_org_id_job_job_id_position import V2OrgOrgIdJobJobIdPosition
from chart_hop_python_sdk.apis.paths.v2_org_org_id_person import V2OrgOrgIdPerson
from chart_hop_python_sdk.apis.paths.v2_org_org_id_person_person_id import V2OrgOrgIdPersonPersonId
from chart_hop_python_sdk.apis.paths.v2_org_org_id_person_geocodes import V2OrgOrgIdPersonGeocodes
from chart_hop_python_sdk.apis.paths.v2_org_org_id_position_position_id import V2OrgOrgIdPositionPositionId
from chart_hop_python_sdk.apis.paths.v2_org_org_id_position_position_id_history import V2OrgOrgIdPositionPositionIdHistory
from chart_hop_python_sdk.apis.paths.v2_org_org_id_position import V2OrgOrgIdPosition
from chart_hop_python_sdk.apis.paths.v2_org_org_id_position_position_id_purge import V2OrgOrgIdPositionPositionIdPurge
from chart_hop_python_sdk.apis.paths.v2_org_org_id_position_position_id_job_job_id import V2OrgOrgIdPositionPositionIdJobJobId
from chart_hop_python_sdk.apis.paths.v2_org_org_id_position_import import V2OrgOrgIdPositionImport

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.V1_ORG_ORG_ID_ACCESS_ENTITY_TYPE: V1OrgOrgIdAccessEntityType,
        PathValues.V1_ORG_ORG_ID_ACTION_ACTION_ID: V1OrgOrgIdActionActionId,
        PathValues.V1_ORG_ORG_ID_ACTION: V1OrgOrgIdAction,
        PathValues.V1_ORG_ORG_ID_ACTION_ACTION_ID_RUN: V1OrgOrgIdActionActionIdRun,
        PathValues.V1_ORG_ORG_ID_AI_FORMRESPONSE_SUMMARY: V1OrgOrgIdAiFormResponseSummary,
        PathValues.V1_APPCONFIG_APP_ID: V1AppConfigAppId,
        PathValues.V1_APPCONFIG_APP_ID_USER_ID: V1AppConfigAppIdUserId,
        PathValues.V1_APPCONFIG: V1AppConfig,
        PathValues.V1_APP_NOTIFY: V1AppNotify,
        PathValues.V1_APP_APP_ID: V1AppAppId,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_APP_USER_ID_TOKEN: V1AppOrgOrgIdInstallAppUserIdToken,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_APP_USER_ID_CODE: V1AppOrgOrgIdInstallAppUserIdCode,
        PathValues.V1_APP: V1App,
        PathValues.V1_APP_ORG_ORG_ID: V1AppOrgOrgId,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_APP_USER_ID_RUN: V1AppOrgOrgIdInstallAppUserIdRun,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_APP_USER_ID: V1AppOrgOrgIdInstallAppUserId,
        PathValues.V1_APP_NAME_APP_NAME: V1AppNameAppName,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_NAME_APP_NAME: V1AppOrgOrgIdInstallNameAppName,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL: V1AppOrgOrgIdInstall,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_VALIDATE: V1AppOrgOrgIdInstallValidate,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_APP_USER_ID_INSTALLDATA_INSTALL_DATA_NAME: V1AppOrgOrgIdInstallAppUserIdInstalldataInstallDataName,
        PathValues.V1_ORG_ORG_ID_APPROVALREQUEST_APPROVAL_REQUEST_ID_SCENARIORESPONSE: V1OrgOrgIdApprovalRequestApprovalRequestIdScenarioResponse,
        PathValues.V1_ORG_ORG_ID_APPROVALREQUEST_SCENARIOJOB_JOB_ID: V1OrgOrgIdApprovalRequestScenarioJobJobId,
        PathValues.V1_ORG_ORG_ID_APPROVALREQUEST_ENTITY_SCENARIO: V1OrgOrgIdApprovalRequestEntityScenario,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN: V1OrgOrgIdApprovalChain,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID: V1OrgOrgIdApprovalChainApprovalChainId,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_REQUEST_APPROVAL_REQUEST_ID: V1OrgOrgIdApprovalChainApprovalChainIdRequestApprovalRequestId,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_REQUEST_ENTITY_COMPREVIEW: V1OrgOrgIdApprovalChainApprovalChainIdRequestEntityCompReview,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_STAGE: V1OrgOrgIdApprovalChainApprovalChainIdStage,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_STAGE_APPROVAL_CHAIN_STAGE_ID: V1OrgOrgIdApprovalChainApprovalChainIdStageApprovalChainStageId,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_CREATEDEFAULTCHAIN: V1OrgOrgIdApprovalChainCreateDefaultChain,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_REQUEST: V1OrgOrgIdApprovalChainApprovalChainIdRequest,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_REQUEST_ENTITY_SCENARIO: V1OrgOrgIdApprovalChainApprovalChainIdRequestEntityScenario,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_REQUEST_APPROVAL_REQUEST_ID_REASSIGNAPPROVER: V1OrgOrgIdApprovalChainApprovalChainIdRequestApprovalRequestIdReassignApprover,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_REQUEST_APPROVAL_REQUEST_ID_SENDREMINDER: V1OrgOrgIdApprovalChainApprovalChainIdRequestApprovalRequestIdSendReminder,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_BULK_DUPLICATE: V1OrgOrgIdAssessmentBulkDuplicate,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_BULK_MOVE: V1OrgOrgIdAssessmentBulkMove,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_BULK_DELETE: V1OrgOrgIdAssessmentBulkDelete,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_ASSESSMENT_ID: V1OrgOrgIdAssessmentAssessmentId,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_ASSESSMENT_ID_COMPLETE: V1OrgOrgIdAssessmentAssessmentIdComplete,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_ASSESSMENT_ID_REACTIVATE: V1OrgOrgIdAssessmentAssessmentIdReactivate,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_ASSESSMENT_ID_FORM_FORM_ID_EXPIRE: V1OrgOrgIdAssessmentAssessmentIdFormFormIdExpire,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT: V1OrgOrgIdAssessment,
        PathValues.V1_CUSTOMER_CUSTOMER_ID_BILLING_CANCEL: V1CustomerCustomerIdBillingCancel,
        PathValues.V1_CUSTOMER_CUSTOMER_ID_BILLING_CHECKOUT: V1CustomerCustomerIdBillingCheckout,
        PathValues.V1_CUSTOMER_CUSTOMER_ID_BILLING: V1CustomerCustomerIdBilling,
        PathValues.V1_ORG_ORG_ID_BUDGETPOOL_ID_GUIDELINES: V1OrgOrgIdBudgetPoolIdGuidelines,
        PathValues.V1_ORG_ORG_ID_BUDGETPOOL_ID_CALCULATE: V1OrgOrgIdBudgetPoolIdCalculate,
        PathValues.V1_ORG_ORG_ID_BUDGETPOOL: V1OrgOrgIdBudgetPool,
        PathValues.V1_ORG_ORG_ID_BUDGETPOOL_ID: V1OrgOrgIdBudgetPoolId,
        PathValues.V1_ORG_ORG_ID_BUDGETPOOL_ID_PREVIEW: V1OrgOrgIdBudgetPoolIdPreview,
        PathValues.V1_ORG_ORG_ID_CALENDAR: V1OrgOrgIdCalendar,
        PathValues.V1_ORG_ORG_ID_CATEGORY: V1OrgOrgIdCategory,
        PathValues.V1_ORG_ORG_ID_CATEGORY_CATEGORY_ID: V1OrgOrgIdCategoryCategoryId,
        PathValues.V1_ORG_ORG_ID_CATEGORYSORT_UPSERT: V1OrgOrgIdCategorySortUpsert,
        PathValues.V1_ORG_ORG_ID_CATEGORYSORT: V1OrgOrgIdCategorySort,
        PathValues.V1_ORG_ORG_ID_CHANGE_BULKUPDATE: V1OrgOrgIdChangeBulkupdate,
        PathValues.V1_ORG_ORG_ID_CHANGE_TYPE_VALIDATE: V1OrgOrgIdChangeTypeValidate,
        PathValues.V1_ORG_ORG_ID_CHANGE_TYPE: V1OrgOrgIdChangeType,
        PathValues.V1_ORG_ORG_ID_CHANGE_CHANGE_ID: V1OrgOrgIdChangeChangeId,
        PathValues.V1_ORG_ORG_ID_CHANGE: V1OrgOrgIdChange,
        PathValues.V1_ORG_ORG_ID_CHANGE_CHANGE_ID_APPROVER: V1OrgOrgIdChangeChangeIdApprover,
        PathValues.V1_ORG_ORG_ID_CHANGE_SCENARIO_SCENARIO_ID: V1OrgOrgIdChangeScenarioScenarioId,
        PathValues.V1_ORG_ORG_ID_CHANGE_SYNC_TYPE: V1OrgOrgIdChangeSyncType,
        PathValues.V1_ORG_ORG_ID_CHANGE_DEPARTREHIRE: V1OrgOrgIdChangeDepartRehire,
        PathValues.V1_ORG_ORG_ID_CHANGE_BULKCHANGE: V1OrgOrgIdChangeBulkchange,
        PathValues.V1_ORG_ORG_ID_CHANGE_CHANGE_ID_APPROVE: V1OrgOrgIdChangeChangeIdApprove,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_CHANGE_CHANGE_ID: V1OrgOrgIdScenarioScenarioIdChangeChangeId,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_CHANGE_CHANGE_ID_STATUS_PROCESS_ID: V1OrgOrgIdScenarioScenarioIdChangeChangeIdStatusProcessId,
        PathValues.V1_ORG_ORG_ID_COMMENT_COMMENT_ID: V1OrgOrgIdCommentCommentId,
        PathValues.V1_ORG_ORG_ID_COMMENT: V1OrgOrgIdComment,
        PathValues.V1_ORG_ORG_ID_COMMENT_ENTITY_ENTITY_ID: V1OrgOrgIdCommentEntityEntityId,
        PathValues.V1_ORG_ORG_ID_COMMENT_COMPREVIEW_COMP_REVIEW_ID: V1OrgOrgIdCommentCompReviewCompReviewId,
        PathValues.V1_ORG_ORG_ID_COMMENT_SCENARIO_SCENARIO_ID: V1OrgOrgIdCommentScenarioScenarioId,
        PathValues.V1_ORG_ORG_ID_BAND_BAND_ID: V1OrgOrgIdBandBandId,
        PathValues.V1_ORG_ORG_ID_BAND: V1OrgOrgIdBand,
        PathValues.V1_ORG_ORG_ID_BAND_RESET: V1OrgOrgIdBandReset,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_BULK_DELETE: V1OrgOrgIdCompReviewBulkDelete,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_BULK_DUPLICATE: V1OrgOrgIdCompReviewBulkDuplicate,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_DUPLICATE: V1OrgOrgIdCompReviewCompReviewIdDuplicate,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID: V1OrgOrgIdCompReviewCompReviewId,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_PAUSE: V1OrgOrgIdCompReviewCompReviewIdPause,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_CONCLUDE: V1OrgOrgIdCompReviewCompReviewIdConclude,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_PREVIEW: V1OrgOrgIdCompReviewCompReviewIdPreview,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_INCYCLE: V1OrgOrgIdCompReviewCompReviewIdInCycle,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW: V1OrgOrgIdCompReview,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_METADATA: V1OrgOrgIdCompReviewCompReviewIdMetadata,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_GENERATE: V1OrgOrgIdCompReviewCompReviewIdGenerate,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_INCYCLE_CHANGES: V1OrgOrgIdCompReviewCompReviewIdInCycleChanges,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_INCYCLE_CHANGES_CHANGE_ID: V1OrgOrgIdCompReviewCompReviewIdInCycleChangesChangeId,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_INCYCLE_COLLABICIENT: V1OrgOrgIdCompReviewCompReviewIdInCycleCollabicient,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_ELIGIBLEEMPLOYEES: V1OrgOrgIdCompReviewCompReviewIdEligibleEmployees,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_ASSOCIATEDENTITIES: V1OrgOrgIdCompReviewCompReviewIdAssociatedEntities,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_SENDREMINDEREMAIL: V1OrgOrgIdCompReviewCompReviewIdSendReminderEmail,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_APPROVALREQUESTS: V1OrgOrgIdCompReviewCompReviewIdApprovalRequests,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_APPROVALREQUESTS_APPROVAL_REQUEST_ID: V1OrgOrgIdCompReviewCompReviewIdApprovalRequestsApprovalRequestId,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_EXPORT: V1OrgOrgIdCompReviewCompReviewIdExport,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_EXPORT_AUDIT: V1OrgOrgIdCompReviewCompReviewIdExportAudit,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_EXPORT_COMMENTS: V1OrgOrgIdCompReviewCompReviewIdExportComments,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_VISUALIZATIONS: V1OrgOrgIdCompReviewCompReviewIdVisualizations,
        PathValues.V1_ORG_ORG_ID_CONTENT_CONTENT_ID: V1OrgOrgIdContentContentId,
        PathValues.V1_ORG_ORG_ID_CONTENT_HOMEPAGE_RENDER: V1OrgOrgIdContentHomepageRender,
        PathValues.V1_ORG_ORG_ID_CONTENT_HOMEPAGE: V1OrgOrgIdContentHomepage,
        PathValues.V1_ORG_ORG_ID_CONTENT: V1OrgOrgIdContent,
        PathValues.V1_ORG_ORG_ID_CONTENT_PATH_PATH: V1OrgOrgIdContentPathPath,
        PathValues.V1_ORG_ORG_ID_CONTENT_PATH_PATH_RENDER: V1OrgOrgIdContentPathPathRender,
        PathValues.V1_CUSTOMER_CUSTOMER_ID_SUBSCRIPTION: V1CustomerCustomerIdSubscription,
        PathValues.V1_CUSTOMER_CUSTOMER_ID: V1CustomerCustomerId,
        PathValues.V1_CUSTOMER: V1Customer,
        PathValues.V1_CUSTOMER_CUSTOMER_ID_INVOICES: V1CustomerCustomerIdInvoices,
        PathValues.V1_ORG_ORG_ID_DATAVIEW: V1OrgOrgIdDataView,
        PathValues.V1_ORG_ORG_ID_DATAVIEW_DATA_VIEW_ID: V1OrgOrgIdDataViewDataViewId,
        PathValues.V1_EMAILTEMPLATE: V1EmailTemplate,
        PathValues.V1_EMAILTEMPLATE_EMAIL_TEMPLATE_ID: V1EmailTemplateEmailTemplateId,
        PathValues.V1_EMAILTEMPLATE_ESSENTIAL: V1EmailTemplateEssential,
        PathValues.V1_EMAILTEMPLATE_NONESSENTIAL: V1EmailTemplateNonEssential,
        PathValues.V1_EMAILTEMPLATE_NAME_NAME: V1EmailTemplateNameName,
        PathValues.V1_ORG_ORG_ID_EVENT_EVENT_ID: V1OrgOrgIdEventEventId,
        PathValues.V1_ORG_ORG_ID_EVENT: V1OrgOrgIdEvent,
        PathValues.V1_ORG_ORG_ID_EVENT_EVENT_ID_NOTIFY: V1OrgOrgIdEventEventIdNotify,
        PathValues.V1_ORG_ORG_ID_EVENT_NOTIFY_INBOUND_APP_ID_INBOUND_ID: V1OrgOrgIdEventNotifyInboundAppIdInboundId,
        PathValues.V1_ORG_ORG_ID_EVENT_NOTIFY_OUTBOUND_APP_APP_ID: V1OrgOrgIdEventNotifyOutboundAppAppId,
        PathValues.V1_ORG_ORG_ID_EXCHANGERATE_DATE_HISTORY: V1OrgOrgIdExchangeRateDateHistory,
        PathValues.V1_ORG_ORG_ID_EXCHANGERATE_DATE_CUSTOM_BULKUPDATE: V1OrgOrgIdExchangeRateDateCustomBulkupdate,
        PathValues.V1_ORG_ORG_ID_EXCHANGERATE_DATE: V1OrgOrgIdExchangeRateDate,
        PathValues.V1_ORG_ORG_ID_EXCHANGERATE_DATE_GLOBAL: V1OrgOrgIdExchangeRateDateGlobal,
        PathValues.V1_ORG_ORG_ID_EXCHANGERATE_DATE_CUSTOM: V1OrgOrgIdExchangeRateDateCustom,
        PathValues.V1_ORG_ORG_ID_EXPORT_POWERPOINT_REPORT_REPORT_ID: V1OrgOrgIdExportPowerpointReportReportId,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_SCENARIO_SCENARIO_ID_COMMENTS: V1OrgOrgIdExportCsvScenarioScenarioIdComments,
        PathValues.V1_ORG_ORG_ID_EXPORT_POWERPOINT_ORG: V1OrgOrgIdExportPowerpointOrg,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_CHANGE: V1OrgOrgIdExportCsvChange,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_USERS: V1OrgOrgIdExportCsvUsers,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_TASK_REVIEW_ID: V1OrgOrgIdExportCsvTaskReviewId,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_SCENARIO_SCENARIO_ID: V1OrgOrgIdExportCsvScenarioScenarioId,
        PathValues.V1_ORG_ORG_ID_EXPORT_PDF_REVIEW_ASSESSMENT_ID: V1OrgOrgIdExportPdfReviewAssessmentId,
        PathValues.V1_ORG_ORG_ID_EXPORT_ZIP_FILE: V1OrgOrgIdExportZipFile,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_FIELDS: V1OrgOrgIdExportCsvFields,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_SNAPSHOT: V1OrgOrgIdExportCsvSnapshot,
        PathValues.V1_ORG_ORG_ID_CQL_VALIDATE: V1OrgOrgIdCqlValidate,
        PathValues.V1_ORG_ORG_ID_CQL_EVALUATE: V1OrgOrgIdCqlEvaluate,
        PathValues.V1_ORG_ORG_ID_FIELD: V1OrgOrgIdField,
        PathValues.V1_ORG_ORG_ID_FIELD_FIELD_ID: V1OrgOrgIdFieldFieldId,
        PathValues.V1_ORG_ORG_ID_FIELD_REMOVEOVERRIDES: V1OrgOrgIdFieldRemoveOverrides,
        PathValues.V1_ORG_ORG_ID_FIELD_REMOVECATEGORY: V1OrgOrgIdFieldRemoveCategory,
        PathValues.V1_ORG_ORG_ID_FIELD_FIELD_ID_DRYRUN: V1OrgOrgIdFieldFieldIdDryrun,
        PathValues.V1_ORG_ORG_ID_FIELD_DELETE: V1OrgOrgIdFieldDelete,
        PathValues.V1_ORG_ORG_ID_FIELD_BUILTIN: V1OrgOrgIdFieldBuiltIn,
        PathValues.V1_ORG_ORG_ID_FIELD_CATEGORY_CATEGORY_ID: V1OrgOrgIdFieldCategoryCategoryId,
        PathValues.V1_ORG_ORG_ID_FIELD_CATEGORY: V1OrgOrgIdFieldCategory,
        PathValues.V1_ORG_ORG_ID_FIELD_STATUS: V1OrgOrgIdFieldStatus,
        PathValues.V1_ORG_ORG_ID_FILE: V1OrgOrgIdFile,
        PathValues.V1_ORG_ORG_ID_FILE_FILE_ID: V1OrgOrgIdFileFileId,
        PathValues.V1_ORG_ORG_ID_FILE_FILE_ID_DOWNLOAD: V1OrgOrgIdFileFileIdDownload,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID: V1OrgOrgIdFormFormId,
        PathValues.V1_ORG_ORG_ID_FORM_DELETE: V1OrgOrgIdFormDelete,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_DRAFT: V1OrgOrgIdFormFormIdDraft,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_SUBMIT_DRAFT: V1OrgOrgIdFormFormIdSubmitDraft,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_SUBMIT: V1OrgOrgIdFormFormIdSubmit,
        PathValues.V1_ORG_ORG_ID_FORM_AVAILABLE: V1OrgOrgIdFormAvailable,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_RENDER: V1OrgOrgIdFormFormIdRender,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_RERENDER_QUESTION_UPDATE_QUESTION_ID: V1OrgOrgIdFormFormIdRerenderQuestionUpdateQuestionId,
        PathValues.V1_ORG_ORG_ID_FORM_DRAFT_DRAFT_ID: V1OrgOrgIdFormDraftDraftId,
        PathValues.V1_ORG_ORG_ID_FORM: V1OrgOrgIdForm,
        PathValues.V1_ORG_ORG_ID_FORM_PERSON_PERSON_ID: V1OrgOrgIdFormPersonPersonId,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_COLLECT: V1OrgOrgIdFormFormIdCollect,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_REMIND: V1OrgOrgIdFormFormIdRemind,
        PathValues.V1_ORG_ORG_ID_FORM_STATUS: V1OrgOrgIdFormStatus,
        PathValues.V1_ORG_ORG_ID_FORMRESPONSE_FORM_RESPONSE_ID: V1OrgOrgIdFormResponseFormResponseId,
        PathValues.V1_ORG_ORG_ID_FORMRESPONSE: V1OrgOrgIdFormResponse,
        PathValues.V1_ORG_ORG_ID_FORMRESPONSE_COUNT: V1OrgOrgIdFormResponseCount,
        PathValues.V1_MEDIA: V1Media,
        PathValues.V1_MEDIA_MEDIA_ID: V1MediaMediaId,
        PathValues.V1_ORG_ORG_ID_GUIDELINE: V1OrgOrgIdGuideline,
        PathValues.V1_ORG_ORG_ID_GUIDELINE_ID: V1OrgOrgIdGuidelineId,
        PathValues.V1_ORG_ORG_ID_GUIDELINE_ID_CALCULATE: V1OrgOrgIdGuidelineIdCalculate,
        PathValues.V1_ORG_ORG_ID_IMPORT_CSV_DATA: V1OrgOrgIdImportCsvData,
        PathValues.V1_ORG_ORG_ID_IMPORT_CSV_COLUMN_MATCH: V1OrgOrgIdImportCsvColumnMatch,
        PathValues.V1_ORG_ORG_ID_IMPORT_CSV_FILEPATH: V1OrgOrgIdImportCsvFilepath,
        PathValues.V1_ORG_ORG_ID_IMPORT_SPREADSHEET_VALIDATE_FORMAT: V1OrgOrgIdImportSpreadsheetValidateFormat,
        PathValues.V1_ORG_ORG_ID_IMPORT_CSV_INITIAL_COLUMN_MATCH: V1OrgOrgIdImportCsvInitialColumnMatch,
        PathValues.V1_ORG_ORG_ID_JOBLEVEL: V1OrgOrgIdJobLevel,
        PathValues.V1_ORG_ORG_ID_JOBLEVEL_JOB_LEVEL_ID: V1OrgOrgIdJobLevelJobLevelId,
        PathValues.V1_LEGALDOC_NAME: V1LegaldocName,
        PathValues.V1_LEGALDOC: V1Legaldoc,
        PathValues.V1_ORG_ORG_ID_MEDIA: V1OrgOrgIdMedia,
        PathValues.V1_ORG_ORG_ID_MEDIA_MEDIA_ID: V1OrgOrgIdMediaMediaId,
        PathValues.V1_ORG_ORG_ID_MESSAGE_MESSAGE_ID: V1OrgOrgIdMessageMessageId,
        PathValues.V1_ORG_ORG_ID_MESSAGE_ME: V1OrgOrgIdMessageMe,
        PathValues.V1_ORG_ORG_ID_MESSAGE: V1OrgOrgIdMessage,
        PathValues.V1_ORG_ORG_ID_MESSAGE_ME_MESSAGE_KEY: V1OrgOrgIdMessageMeMessageKey,
        PathValues.V1_ORG_ORG_ID_MESSAGE_MESSAGE_ID_READ: V1OrgOrgIdMessageMessageIdRead,
        PathValues.V1_ORG_ORG_ID_MESSAGE_BULK_READ: V1OrgOrgIdMessageBulkRead,
        PathValues.V1_ORG_ORG_ID_MESSAGE_BULK_SEEN: V1OrgOrgIdMessageBulkSeen,
        PathValues.V1_ORG_ORG_ID_METRIC: V1OrgOrgIdMetric,
        PathValues.V1_ORG_ORG_ID_MULTIPLIER_MULTIPLIER_ID: V1OrgOrgIdMultiplierMultiplierId,
        PathValues.V1_ORG_ORG_ID_MULTIPLIER: V1OrgOrgIdMultiplier,
        PathValues.V1_ORG_ORG_ID_NOTIFICATION: V1OrgOrgIdNotification,
        PathValues.OAUTH_TOKEN: OauthToken,
        PathValues.OAUTH_APP_APP_NAME: OauthAppAppName,
        PathValues.OAUTH_SSO_IDP_LOGIN: OauthSsoIdpLogin,
        PathValues.OAUTH_SSO_IDP_ACCESSTOKEN: OauthSsoIdpAccessToken,
        PathValues.OAUTH_TOKEN_VIEW: OauthTokenView,
        PathValues.OAUTH_TOKEN_SSO_TYPE: OauthTokenSsoType,
        PathValues.V1_ORG_ORG_ID_ONBOARD: V1OrgOrgIdOnboard,
        PathValues.V1_ORG_ORG_ID_ONBOARD_STEP_NAME_SKIP: V1OrgOrgIdOnboardStepNameSkip,
        PathValues.V1_ORG_ORG_ID_CONFIG: V1OrgOrgIdConfig,
        PathValues.V1_ORG: V1Org,
        PathValues.V1_ORG_ORG_ID: V1OrgOrgId,
        PathValues.V1_ORG_ORG_ID_DATAUSERSPERSONS: V1OrgOrgIdDataUsersPersons,
        PathValues.V1_ORG_ORG_ID_CHANGEHEAD: V1OrgOrgIdChangeHead,
        PathValues.V1_ORG_ORG_ID_WELCOMEEMAIL: V1OrgOrgIdWelcomeEmail,
        PathValues.V1_ORG_ORG_ID_TESTEMAIL: V1OrgOrgIdTestEmail,
        PathValues.V1_ORG_ORG_ID_AGREEMENT: V1OrgOrgIdAgreement,
        PathValues.V1_ORG_ORG_ID_ACCESS: V1OrgOrgIdAccess,
        PathValues.V1_ORG_ORG_ID_DATAUSERPERSONCOUNT: V1OrgOrgIdDataUserPersonCount,
        PathValues.V1_ORG_ORG_ID_DATAUSERPERSON: V1OrgOrgIdDataUserPerson,
        PathValues.V1_ORG_ORG_APPINSTALLCODE: V1OrgOrgAppInstallCode,
        PathValues.V1_ORG_APPINSTALLCODE_VALIDATE: V1OrgAppInstallCodeValidate,
        PathValues.ORG_SLUG: OrgSlug,
        PathValues.V1_ORG_SLUG_SLUG: V1OrgSlugSlug,
        PathValues.V1_ORG_ORG_ID_POLICY_POLICY_ID: V1OrgOrgIdPolicyPolicyId,
        PathValues.V1_ORG_ORG_ID_POLICY: V1OrgOrgIdPolicy,
        PathValues.V1_ORG_ORG_ID_POLICY_POLICY_ID_COPY: V1OrgOrgIdPolicyPolicyIdCopy,
        PathValues.V1_ORG_ORG_ID_POLICY_VALIDATE: V1OrgOrgIdPolicyValidate,
        PathValues.V1_ORG_ORG_ID_POLICY_ACTION: V1OrgOrgIdPolicyAction,
        PathValues.V1_ORG_ORG_ID_PRELOAD: V1OrgOrgIdPreload,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_DECREMENT: V1OrgOrgIdProcessProcessIdDecrement,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_INCREMENT: V1OrgOrgIdProcessProcessIdIncrement,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_RESUME: V1OrgOrgIdProcessProcessIdResume,
        PathValues.V1_ORG_ORG_ID_PROCESS: V1OrgOrgIdProcess,
        PathValues.V1_ORG_ORG_ID_PROCESS_SELFSERVE: V1OrgOrgIdProcessSelfServe,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_STATE: V1OrgOrgIdProcessProcessIdState,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_RESUME_WITH_FILE: V1OrgOrgIdProcessProcessIdResumeWithFile,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_EVENTS: V1OrgOrgIdProcessProcessIdEvents,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_FILE: V1OrgOrgIdProcessProcessIdFile,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_LOG: V1OrgOrgIdProcessProcessIdLog,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID: V1OrgOrgIdProcessProcessId,
        PathValues.V1_ORG_ORG_ID_PROCESS_LASTSYNC_APP_USER_ID: V1OrgOrgIdProcessLastSyncAppUserId,
        PathValues.V1_ORG_ORG_ID_PROCESS_CREATE_ID_OVERRIDE: V1OrgOrgIdProcessCreateIdOverride,
        PathValues.V1_PRODUCT_PRODUCT_ID: V1ProductProductId,
        PathValues.V1_PRODUCT: V1Product,
        PathValues.V1_ORG_ORG_ID_PROFILETAB_JOB_JOB_ID_PROFILETAB_TAB_ID: V1OrgOrgIdProfileTabJobJobIdProfileTabTabId,
        PathValues.V1_ORG_ORG_ID_PROFILETAB_PROFILE_TAB_ID: V1OrgOrgIdProfileTabProfileTabId,
        PathValues.V1_ORG_ORG_ID_PROFILETAB: V1OrgOrgIdProfileTab,
        PathValues.V1_ORG_ORG_ID_PROFILETAB_PERSON_PERSON_ID: V1OrgOrgIdProfileTabPersonPersonId,
        PathValues.V1_ORG_ORG_ID_PROFILETAB_JOB_JOB_ID: V1OrgOrgIdProfileTabJobJobId,
        PathValues.V1_ORG_ORG_ID_QUERY_QUERY_TOKEN: V1OrgOrgIdQueryQueryToken,
        PathValues.V1_ORG_ORG_ID_QUERY: V1OrgOrgIdQuery,
        PathValues.V1_ORG_ORG_ID_QUESTION_QUESTION_ID: V1OrgOrgIdQuestionQuestionId,
        PathValues.V1_ORG_ORG_ID_QUESTION: V1OrgOrgIdQuestion,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_CHART: V1OrgOrgIdReportReportIdChart,
        PathValues.V1_ORG_ORG_ID_REPORT_CHART_CHART_ID: V1OrgOrgIdReportChartChartId,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_CHART_CHART_ID_CLONE: V1OrgOrgIdReportReportIdChartChartIdClone,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_CHART_CHART_ID_DATA: V1OrgOrgIdReportReportIdChartChartIdData,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_CHART_CHART_ID_QUERY: V1OrgOrgIdReportReportIdChartChartIdQuery,
        PathValues.V1_ORG_ORG_ID_REPORT: V1OrgOrgIdReport,
        PathValues.V1_ORG_ORG_ID_REPORT_COUNT: V1OrgOrgIdReportCount,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID: V1OrgOrgIdReportReportId,
        PathValues.V1_ORG_ORG_ID_REPORT_QUERY: V1OrgOrgIdReportQuery,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_QUERY: V1OrgOrgIdReportReportIdQuery,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_CHART_CHART_ID_EXPORT_CSV: V1OrgOrgIdReportReportIdChartChartIdExportCsv,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_CLONE: V1OrgOrgIdReportReportIdClone,
        PathValues.V1_ORG_ORG_ID_REPORT_BULKDELETE: V1OrgOrgIdReportBulkDelete,
        PathValues.V1_ORG_ORG_ID_REPORT_BULKDUPLICATE: V1OrgOrgIdReportBulkDuplicate,
        PathValues.V1_ORG_ORG_ID_ROLE: V1OrgOrgIdRole,
        PathValues.V1_ORG_ORG_ID_ROLE_ROLE_ID: V1OrgOrgIdRoleRoleId,
        PathValues.V1_ORG_ORG_ID_ROLE_ROLE_ID_COPY: V1OrgOrgIdRoleRoleIdCopy,
        PathValues.SAML_ORG_LOGIN: SamlOrgLogin,
        PathValues.SAML_SSO_ORG: SamlSsoOrg,
        PathValues.SAML_ORG_ORG_ID_XMLCERT: SamlOrgOrgIdXmlCert,
        PathValues.V1_ORG_ORG_ID_SCENARIO_BULK_ARCHIVE: V1OrgOrgIdScenarioBulkArchive,
        PathValues.V1_ORG_ORG_ID_SCENARIO_BULK_DELETE: V1OrgOrgIdScenarioBulkDelete,
        PathValues.V1_ORG_ORG_ID_SCENARIO_BULK_UNARCHIVE: V1OrgOrgIdScenarioBulkUnarchive,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID: V1OrgOrgIdScenarioScenarioId,
        PathValues.V1_ORG_ORG_ID_SCENARIO: V1OrgOrgIdScenario,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_DATES: V1OrgOrgIdScenarioScenarioIdDates,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_MERGE: V1OrgOrgIdScenarioScenarioIdMerge,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_COMBINE: V1OrgOrgIdScenarioScenarioIdCombine,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_RECALCULATEMETADATA: V1OrgOrgIdScenarioScenarioIdRecalculateMetadata,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_UPDATESHAREDVIEW: V1OrgOrgIdScenarioScenarioIdUpdateSharedView,
        PathValues.V1_ORG_ORG_ID_SEARCH: V1OrgOrgIdSearch,
        PathValues.V1_STATUS: V1Status,
        PathValues.V1_STOCK: V1Stock,
        PathValues.V1_STOCK_ID: V1StockId,
        PathValues.V1_STOCK_SYMBOL_DATE_TYPE: V1StockSymbolDateType,
        PathValues.V1_STRIPE_SETUPINTENT: V1StripeSetupIntent,
        PathValues.V1_STRIPE_PLAN: V1StripePlan,
        PathValues.V1_STRIPE_WEBHOOK: V1StripeWebhook,
        PathValues.V1_STRIPE_PRODUCT_PRODUCT_ID: V1StripeProductProductId,
        PathValues.V1_STRIPE_PRODUCT: V1StripeProduct,
        PathValues.V1_ORG_ORG_ID_TABLE_TABLE_ID: V1OrgOrgIdTableTableId,
        PathValues.V1_ORG_ORG_ID_TABLE_TABLE_ID_IMPORT: V1OrgOrgIdTableTableIdImport,
        PathValues.V1_ORG_ORG_ID_TABLE: V1OrgOrgIdTable,
        PathValues.V1_ORG_ORG_ID_TABLE_TABLE_ID_DATA: V1OrgOrgIdTableTableIdData,
        PathValues.V1_ORG_ORG_ID_TABLE_TABLE_ID_DATA_KEY_COLUMN_KEY_VALUE: V1OrgOrgIdTableTableIdDataKeyColumnKeyValue,
        PathValues.V1_ORG_ORG_ID_TABLE_TABLE_ID_DATA_KEY_COLUMN_KEY_VALUE_PURGE: V1OrgOrgIdTableTableIdDataKeyColumnKeyValuePurge,
        PathValues.V1_ORG_ORG_ID_TABLE_TABLE_ID_EXPORT: V1OrgOrgIdTableTableIdExport,
        PathValues.V1_ORG_ORG_ID_TASKCONFIG: V1OrgOrgIdTaskConfig,
        PathValues.V1_ORG_ORG_ID_TASKCONFIG_ID: V1OrgOrgIdTaskConfigId,
        PathValues.V1_ORG_ORG_ID_TASK_TASK_ID_MARKDONE: V1OrgOrgIdTaskTaskIdMarkDone,
        PathValues.V1_ORG_ORG_ID_TASK_TASK_ID_SKIP: V1OrgOrgIdTaskTaskIdSkip,
        PathValues.V1_ORG_ORG_ID_TASK: V1OrgOrgIdTask,
        PathValues.V1_ORG_ORG_ID_TASK_TASK: V1OrgOrgIdTaskTask,
        PathValues.V1_ORG_ORG_ID_TASK_ME: V1OrgOrgIdTaskMe,
        PathValues.V1_ORG_ORG_ID_TASK_REMIND: V1OrgOrgIdTaskRemind,
        PathValues.V1_ORG_ORG_ID_TASK_TASK_ID: V1OrgOrgIdTaskTaskId,
        PathValues.V1_ORG_ORG_ID_TASK_BULKDELETE: V1OrgOrgIdTaskBulkDelete,
        PathValues.V1_ORG_ORG_ID_TASK_ASSESSMENT_ID_FORM_ID: V1OrgOrgIdTaskAssessmentIdFormId,
        PathValues.V1_ORG_ORG_ID_TASK_SUMMARY_ASSESSMENT_ID: V1OrgOrgIdTaskSummaryAssessmentId,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_BULK_DELETE: V1OrgOrgIdTemplateBulkDelete,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_BULK_DUPLICATE: V1OrgOrgIdTemplateBulkDuplicate,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_TEMPLATE_ID: V1OrgOrgIdTemplateTemplateId,
        PathValues.V1_ORG_ORG_ID_TEMPLATE: V1OrgOrgIdTemplate,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_TEMPLATE_ID_RENDER: V1OrgOrgIdTemplateTemplateIdRender,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_TEMPLATE_ID_PREVIEW: V1OrgOrgIdTemplateTemplateIdPreview,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_TEMPLATE_ID_GENERATE: V1OrgOrgIdTemplateTemplateIdGenerate,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_EMAIL_TEMPLATE_NAME: V1OrgOrgIdTemplateEmailTemplateName,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_EMAIL: V1OrgOrgIdTemplateEmail,
        PathValues.V1_ORG_ORG_ID_TIMEOFF_REQUEST_VALIDATE: V1OrgOrgIdTimeoffRequestValidate,
        PathValues.V1_ORG_ORG_ID_TIMEOFF: V1OrgOrgIdTimeoff,
        PathValues.V1_ORG_ORG_ID_TIMEOFF_TIME_OFF_ID: V1OrgOrgIdTimeoffTimeOffId,
        PathValues.V1_ORG_ORG_ID_TIMEOFF_REQUEST: V1OrgOrgIdTimeoffRequest,
        PathValues.V1_ORG_ORG_ID_TIMEOFF_TIME_OFF_ID_APPROVE: V1OrgOrgIdTimeoffTimeOffIdApprove,
        PathValues.V1_ORG_ORG_ID_TIMEOFF_TIME_OFF_ID_REJECT: V1OrgOrgIdTimeoffTimeOffIdReject,
        PathValues.V1_ORG_ORG_ID_USAGE_TYPE: V1OrgOrgIdUsageType,
        PathValues.V1_USER_USER_ID: V1UserUserId,
        PathValues.V1_USER: V1User,
        PathValues.V1_USER_USER_ID_TOKEN: V1UserUserIdToken,
        PathValues.V1_USER_TOKEN: V1UserToken,
        PathValues.V1_USER_ASSIGN: V1UserAssign,
        PathValues.V1_USER_ME: V1UserMe,
        PathValues.V1_USER_ME_VIEW: V1UserMeView,
        PathValues.V1_USER_EMAIL_EMAIL: V1UserEmailEmail,
        PathValues.V1_USER_PERSON_PERSON_ID: V1UserPersonPersonId,
        PathValues.V1_USER_INVITE: V1UserInvite,
        PathValues.V1_USER_USER_ID_PASSWORD: V1UserUserIdPassword,
        PathValues.V1_USER_SENDRESET: V1UserSendreset,
        PathValues.V1_WEBAUTHN_REGISTER: V1WebauthnRegister,
        PathValues.V1_WEBAUTHN_REGISTER_EMAIL_BASE64: V1WebauthnRegisterEmailBase64,
        PathValues.V1_WEBAUTHN_VERIFY: V1WebauthnVerify,
        PathValues.V2_ORG_ORG_ID_CHANGE_CHANGE_ID: V2OrgOrgIdChangeChangeId,
        PathValues.V2_ORG_ORG_ID_CHANGE: V2OrgOrgIdChange,
        PathValues.V2_ORG_ORG_ID_GROUP_TYPE: V2OrgOrgIdGroupType,
        PathValues.V2_ORG_ORG_ID_GROUP_TYPE_GROUP_ID: V2OrgOrgIdGroupTypeGroupId,
        PathValues.V2_ORG_ORG_ID_GROUP_COUNT: V2OrgOrgIdGroupCount,
        PathValues.V2_ORG_ORG_ID_GROUP_TYPE_BULKDELETE: V2OrgOrgIdGroupTypeBulkDelete,
        PathValues.V2_ORG_ORG_ID_GROUP_TYPE_IMPORT: V2OrgOrgIdGroupTypeImport,
        PathValues.V2_ORG_ORG_ID_GROUP_GRAPH: V2OrgOrgIdGroupGraph,
        PathValues.V2_ORG_ORG_ID_GROUP_ORPHANED: V2OrgOrgIdGroupOrphaned,
        PathValues.V2_ORG_ORG_ID_JOB_JOB_ID: V2OrgOrgIdJobJobId,
        PathValues.V2_ORG_ORG_ID_JOB_COUNT: V2OrgOrgIdJobCount,
        PathValues.V2_ORG_ORG_ID_JOB_BULKUPDATE: V2OrgOrgIdJobBulkupdate,
        PathValues.V2_ORG_ORG_ID_JOB_GRAPH: V2OrgOrgIdJobGraph,
        PathValues.V2_ORG_ORG_ID_JOB_GRAPHCOUNTS: V2OrgOrgIdJobGraphCounts,
        PathValues.V2_ORG_ORG_ID_JOB: V2OrgOrgIdJob,
        PathValues.V2_ORG_ORG_ID_JOB_JOB_ID_POSITION: V2OrgOrgIdJobJobIdPosition,
        PathValues.V2_ORG_ORG_ID_PERSON: V2OrgOrgIdPerson,
        PathValues.V2_ORG_ORG_ID_PERSON_PERSON_ID: V2OrgOrgIdPersonPersonId,
        PathValues.V2_ORG_ORG_ID_PERSON_GEOCODES: V2OrgOrgIdPersonGeocodes,
        PathValues.V2_ORG_ORG_ID_POSITION_POSITION_ID: V2OrgOrgIdPositionPositionId,
        PathValues.V2_ORG_ORG_ID_POSITION_POSITION_ID_HISTORY: V2OrgOrgIdPositionPositionIdHistory,
        PathValues.V2_ORG_ORG_ID_POSITION: V2OrgOrgIdPosition,
        PathValues.V2_ORG_ORG_ID_POSITION_POSITION_ID_PURGE: V2OrgOrgIdPositionPositionIdPurge,
        PathValues.V2_ORG_ORG_ID_POSITION_POSITION_ID_JOB_JOB_ID: V2OrgOrgIdPositionPositionIdJobJobId,
        PathValues.V2_ORG_ORG_ID_POSITION_IMPORT: V2OrgOrgIdPositionImport,
    }
)

path_to_api = PathToApi(
    {
        PathValues.V1_ORG_ORG_ID_ACCESS_ENTITY_TYPE: V1OrgOrgIdAccessEntityType,
        PathValues.V1_ORG_ORG_ID_ACTION_ACTION_ID: V1OrgOrgIdActionActionId,
        PathValues.V1_ORG_ORG_ID_ACTION: V1OrgOrgIdAction,
        PathValues.V1_ORG_ORG_ID_ACTION_ACTION_ID_RUN: V1OrgOrgIdActionActionIdRun,
        PathValues.V1_ORG_ORG_ID_AI_FORMRESPONSE_SUMMARY: V1OrgOrgIdAiFormResponseSummary,
        PathValues.V1_APPCONFIG_APP_ID: V1AppConfigAppId,
        PathValues.V1_APPCONFIG_APP_ID_USER_ID: V1AppConfigAppIdUserId,
        PathValues.V1_APPCONFIG: V1AppConfig,
        PathValues.V1_APP_NOTIFY: V1AppNotify,
        PathValues.V1_APP_APP_ID: V1AppAppId,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_APP_USER_ID_TOKEN: V1AppOrgOrgIdInstallAppUserIdToken,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_APP_USER_ID_CODE: V1AppOrgOrgIdInstallAppUserIdCode,
        PathValues.V1_APP: V1App,
        PathValues.V1_APP_ORG_ORG_ID: V1AppOrgOrgId,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_APP_USER_ID_RUN: V1AppOrgOrgIdInstallAppUserIdRun,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_APP_USER_ID: V1AppOrgOrgIdInstallAppUserId,
        PathValues.V1_APP_NAME_APP_NAME: V1AppNameAppName,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_NAME_APP_NAME: V1AppOrgOrgIdInstallNameAppName,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL: V1AppOrgOrgIdInstall,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_VALIDATE: V1AppOrgOrgIdInstallValidate,
        PathValues.V1_APP_ORG_ORG_ID_INSTALL_APP_USER_ID_INSTALLDATA_INSTALL_DATA_NAME: V1AppOrgOrgIdInstallAppUserIdInstalldataInstallDataName,
        PathValues.V1_ORG_ORG_ID_APPROVALREQUEST_APPROVAL_REQUEST_ID_SCENARIORESPONSE: V1OrgOrgIdApprovalRequestApprovalRequestIdScenarioResponse,
        PathValues.V1_ORG_ORG_ID_APPROVALREQUEST_SCENARIOJOB_JOB_ID: V1OrgOrgIdApprovalRequestScenarioJobJobId,
        PathValues.V1_ORG_ORG_ID_APPROVALREQUEST_ENTITY_SCENARIO: V1OrgOrgIdApprovalRequestEntityScenario,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN: V1OrgOrgIdApprovalChain,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID: V1OrgOrgIdApprovalChainApprovalChainId,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_REQUEST_APPROVAL_REQUEST_ID: V1OrgOrgIdApprovalChainApprovalChainIdRequestApprovalRequestId,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_REQUEST_ENTITY_COMPREVIEW: V1OrgOrgIdApprovalChainApprovalChainIdRequestEntityCompReview,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_STAGE: V1OrgOrgIdApprovalChainApprovalChainIdStage,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_STAGE_APPROVAL_CHAIN_STAGE_ID: V1OrgOrgIdApprovalChainApprovalChainIdStageApprovalChainStageId,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_CREATEDEFAULTCHAIN: V1OrgOrgIdApprovalChainCreateDefaultChain,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_REQUEST: V1OrgOrgIdApprovalChainApprovalChainIdRequest,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_REQUEST_ENTITY_SCENARIO: V1OrgOrgIdApprovalChainApprovalChainIdRequestEntityScenario,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_REQUEST_APPROVAL_REQUEST_ID_REASSIGNAPPROVER: V1OrgOrgIdApprovalChainApprovalChainIdRequestApprovalRequestIdReassignApprover,
        PathValues.V1_ORG_ORG_ID_APPROVALCHAIN_APPROVAL_CHAIN_ID_REQUEST_APPROVAL_REQUEST_ID_SENDREMINDER: V1OrgOrgIdApprovalChainApprovalChainIdRequestApprovalRequestIdSendReminder,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_BULK_DUPLICATE: V1OrgOrgIdAssessmentBulkDuplicate,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_BULK_MOVE: V1OrgOrgIdAssessmentBulkMove,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_BULK_DELETE: V1OrgOrgIdAssessmentBulkDelete,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_ASSESSMENT_ID: V1OrgOrgIdAssessmentAssessmentId,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_ASSESSMENT_ID_COMPLETE: V1OrgOrgIdAssessmentAssessmentIdComplete,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_ASSESSMENT_ID_REACTIVATE: V1OrgOrgIdAssessmentAssessmentIdReactivate,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT_ASSESSMENT_ID_FORM_FORM_ID_EXPIRE: V1OrgOrgIdAssessmentAssessmentIdFormFormIdExpire,
        PathValues.V1_ORG_ORG_ID_ASSESSMENT: V1OrgOrgIdAssessment,
        PathValues.V1_CUSTOMER_CUSTOMER_ID_BILLING_CANCEL: V1CustomerCustomerIdBillingCancel,
        PathValues.V1_CUSTOMER_CUSTOMER_ID_BILLING_CHECKOUT: V1CustomerCustomerIdBillingCheckout,
        PathValues.V1_CUSTOMER_CUSTOMER_ID_BILLING: V1CustomerCustomerIdBilling,
        PathValues.V1_ORG_ORG_ID_BUDGETPOOL_ID_GUIDELINES: V1OrgOrgIdBudgetPoolIdGuidelines,
        PathValues.V1_ORG_ORG_ID_BUDGETPOOL_ID_CALCULATE: V1OrgOrgIdBudgetPoolIdCalculate,
        PathValues.V1_ORG_ORG_ID_BUDGETPOOL: V1OrgOrgIdBudgetPool,
        PathValues.V1_ORG_ORG_ID_BUDGETPOOL_ID: V1OrgOrgIdBudgetPoolId,
        PathValues.V1_ORG_ORG_ID_BUDGETPOOL_ID_PREVIEW: V1OrgOrgIdBudgetPoolIdPreview,
        PathValues.V1_ORG_ORG_ID_CALENDAR: V1OrgOrgIdCalendar,
        PathValues.V1_ORG_ORG_ID_CATEGORY: V1OrgOrgIdCategory,
        PathValues.V1_ORG_ORG_ID_CATEGORY_CATEGORY_ID: V1OrgOrgIdCategoryCategoryId,
        PathValues.V1_ORG_ORG_ID_CATEGORYSORT_UPSERT: V1OrgOrgIdCategorySortUpsert,
        PathValues.V1_ORG_ORG_ID_CATEGORYSORT: V1OrgOrgIdCategorySort,
        PathValues.V1_ORG_ORG_ID_CHANGE_BULKUPDATE: V1OrgOrgIdChangeBulkupdate,
        PathValues.V1_ORG_ORG_ID_CHANGE_TYPE_VALIDATE: V1OrgOrgIdChangeTypeValidate,
        PathValues.V1_ORG_ORG_ID_CHANGE_TYPE: V1OrgOrgIdChangeType,
        PathValues.V1_ORG_ORG_ID_CHANGE_CHANGE_ID: V1OrgOrgIdChangeChangeId,
        PathValues.V1_ORG_ORG_ID_CHANGE: V1OrgOrgIdChange,
        PathValues.V1_ORG_ORG_ID_CHANGE_CHANGE_ID_APPROVER: V1OrgOrgIdChangeChangeIdApprover,
        PathValues.V1_ORG_ORG_ID_CHANGE_SCENARIO_SCENARIO_ID: V1OrgOrgIdChangeScenarioScenarioId,
        PathValues.V1_ORG_ORG_ID_CHANGE_SYNC_TYPE: V1OrgOrgIdChangeSyncType,
        PathValues.V1_ORG_ORG_ID_CHANGE_DEPARTREHIRE: V1OrgOrgIdChangeDepartRehire,
        PathValues.V1_ORG_ORG_ID_CHANGE_BULKCHANGE: V1OrgOrgIdChangeBulkchange,
        PathValues.V1_ORG_ORG_ID_CHANGE_CHANGE_ID_APPROVE: V1OrgOrgIdChangeChangeIdApprove,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_CHANGE_CHANGE_ID: V1OrgOrgIdScenarioScenarioIdChangeChangeId,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_CHANGE_CHANGE_ID_STATUS_PROCESS_ID: V1OrgOrgIdScenarioScenarioIdChangeChangeIdStatusProcessId,
        PathValues.V1_ORG_ORG_ID_COMMENT_COMMENT_ID: V1OrgOrgIdCommentCommentId,
        PathValues.V1_ORG_ORG_ID_COMMENT: V1OrgOrgIdComment,
        PathValues.V1_ORG_ORG_ID_COMMENT_ENTITY_ENTITY_ID: V1OrgOrgIdCommentEntityEntityId,
        PathValues.V1_ORG_ORG_ID_COMMENT_COMPREVIEW_COMP_REVIEW_ID: V1OrgOrgIdCommentCompReviewCompReviewId,
        PathValues.V1_ORG_ORG_ID_COMMENT_SCENARIO_SCENARIO_ID: V1OrgOrgIdCommentScenarioScenarioId,
        PathValues.V1_ORG_ORG_ID_BAND_BAND_ID: V1OrgOrgIdBandBandId,
        PathValues.V1_ORG_ORG_ID_BAND: V1OrgOrgIdBand,
        PathValues.V1_ORG_ORG_ID_BAND_RESET: V1OrgOrgIdBandReset,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_BULK_DELETE: V1OrgOrgIdCompReviewBulkDelete,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_BULK_DUPLICATE: V1OrgOrgIdCompReviewBulkDuplicate,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_DUPLICATE: V1OrgOrgIdCompReviewCompReviewIdDuplicate,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID: V1OrgOrgIdCompReviewCompReviewId,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_PAUSE: V1OrgOrgIdCompReviewCompReviewIdPause,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_CONCLUDE: V1OrgOrgIdCompReviewCompReviewIdConclude,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_PREVIEW: V1OrgOrgIdCompReviewCompReviewIdPreview,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_INCYCLE: V1OrgOrgIdCompReviewCompReviewIdInCycle,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW: V1OrgOrgIdCompReview,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_METADATA: V1OrgOrgIdCompReviewCompReviewIdMetadata,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_GENERATE: V1OrgOrgIdCompReviewCompReviewIdGenerate,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_INCYCLE_CHANGES: V1OrgOrgIdCompReviewCompReviewIdInCycleChanges,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_INCYCLE_CHANGES_CHANGE_ID: V1OrgOrgIdCompReviewCompReviewIdInCycleChangesChangeId,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_INCYCLE_COLLABICIENT: V1OrgOrgIdCompReviewCompReviewIdInCycleCollabicient,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_ELIGIBLEEMPLOYEES: V1OrgOrgIdCompReviewCompReviewIdEligibleEmployees,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_ASSOCIATEDENTITIES: V1OrgOrgIdCompReviewCompReviewIdAssociatedEntities,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_SENDREMINDEREMAIL: V1OrgOrgIdCompReviewCompReviewIdSendReminderEmail,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_APPROVALREQUESTS: V1OrgOrgIdCompReviewCompReviewIdApprovalRequests,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_APPROVALREQUESTS_APPROVAL_REQUEST_ID: V1OrgOrgIdCompReviewCompReviewIdApprovalRequestsApprovalRequestId,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_EXPORT: V1OrgOrgIdCompReviewCompReviewIdExport,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_EXPORT_AUDIT: V1OrgOrgIdCompReviewCompReviewIdExportAudit,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_EXPORT_COMMENTS: V1OrgOrgIdCompReviewCompReviewIdExportComments,
        PathValues.V1_ORG_ORG_ID_COMPREVIEW_COMP_REVIEW_ID_VISUALIZATIONS: V1OrgOrgIdCompReviewCompReviewIdVisualizations,
        PathValues.V1_ORG_ORG_ID_CONTENT_CONTENT_ID: V1OrgOrgIdContentContentId,
        PathValues.V1_ORG_ORG_ID_CONTENT_HOMEPAGE_RENDER: V1OrgOrgIdContentHomepageRender,
        PathValues.V1_ORG_ORG_ID_CONTENT_HOMEPAGE: V1OrgOrgIdContentHomepage,
        PathValues.V1_ORG_ORG_ID_CONTENT: V1OrgOrgIdContent,
        PathValues.V1_ORG_ORG_ID_CONTENT_PATH_PATH: V1OrgOrgIdContentPathPath,
        PathValues.V1_ORG_ORG_ID_CONTENT_PATH_PATH_RENDER: V1OrgOrgIdContentPathPathRender,
        PathValues.V1_CUSTOMER_CUSTOMER_ID_SUBSCRIPTION: V1CustomerCustomerIdSubscription,
        PathValues.V1_CUSTOMER_CUSTOMER_ID: V1CustomerCustomerId,
        PathValues.V1_CUSTOMER: V1Customer,
        PathValues.V1_CUSTOMER_CUSTOMER_ID_INVOICES: V1CustomerCustomerIdInvoices,
        PathValues.V1_ORG_ORG_ID_DATAVIEW: V1OrgOrgIdDataView,
        PathValues.V1_ORG_ORG_ID_DATAVIEW_DATA_VIEW_ID: V1OrgOrgIdDataViewDataViewId,
        PathValues.V1_EMAILTEMPLATE: V1EmailTemplate,
        PathValues.V1_EMAILTEMPLATE_EMAIL_TEMPLATE_ID: V1EmailTemplateEmailTemplateId,
        PathValues.V1_EMAILTEMPLATE_ESSENTIAL: V1EmailTemplateEssential,
        PathValues.V1_EMAILTEMPLATE_NONESSENTIAL: V1EmailTemplateNonEssential,
        PathValues.V1_EMAILTEMPLATE_NAME_NAME: V1EmailTemplateNameName,
        PathValues.V1_ORG_ORG_ID_EVENT_EVENT_ID: V1OrgOrgIdEventEventId,
        PathValues.V1_ORG_ORG_ID_EVENT: V1OrgOrgIdEvent,
        PathValues.V1_ORG_ORG_ID_EVENT_EVENT_ID_NOTIFY: V1OrgOrgIdEventEventIdNotify,
        PathValues.V1_ORG_ORG_ID_EVENT_NOTIFY_INBOUND_APP_ID_INBOUND_ID: V1OrgOrgIdEventNotifyInboundAppIdInboundId,
        PathValues.V1_ORG_ORG_ID_EVENT_NOTIFY_OUTBOUND_APP_APP_ID: V1OrgOrgIdEventNotifyOutboundAppAppId,
        PathValues.V1_ORG_ORG_ID_EXCHANGERATE_DATE_HISTORY: V1OrgOrgIdExchangeRateDateHistory,
        PathValues.V1_ORG_ORG_ID_EXCHANGERATE_DATE_CUSTOM_BULKUPDATE: V1OrgOrgIdExchangeRateDateCustomBulkupdate,
        PathValues.V1_ORG_ORG_ID_EXCHANGERATE_DATE: V1OrgOrgIdExchangeRateDate,
        PathValues.V1_ORG_ORG_ID_EXCHANGERATE_DATE_GLOBAL: V1OrgOrgIdExchangeRateDateGlobal,
        PathValues.V1_ORG_ORG_ID_EXCHANGERATE_DATE_CUSTOM: V1OrgOrgIdExchangeRateDateCustom,
        PathValues.V1_ORG_ORG_ID_EXPORT_POWERPOINT_REPORT_REPORT_ID: V1OrgOrgIdExportPowerpointReportReportId,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_SCENARIO_SCENARIO_ID_COMMENTS: V1OrgOrgIdExportCsvScenarioScenarioIdComments,
        PathValues.V1_ORG_ORG_ID_EXPORT_POWERPOINT_ORG: V1OrgOrgIdExportPowerpointOrg,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_CHANGE: V1OrgOrgIdExportCsvChange,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_USERS: V1OrgOrgIdExportCsvUsers,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_TASK_REVIEW_ID: V1OrgOrgIdExportCsvTaskReviewId,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_SCENARIO_SCENARIO_ID: V1OrgOrgIdExportCsvScenarioScenarioId,
        PathValues.V1_ORG_ORG_ID_EXPORT_PDF_REVIEW_ASSESSMENT_ID: V1OrgOrgIdExportPdfReviewAssessmentId,
        PathValues.V1_ORG_ORG_ID_EXPORT_ZIP_FILE: V1OrgOrgIdExportZipFile,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_FIELDS: V1OrgOrgIdExportCsvFields,
        PathValues.V1_ORG_ORG_ID_EXPORT_CSV_SNAPSHOT: V1OrgOrgIdExportCsvSnapshot,
        PathValues.V1_ORG_ORG_ID_CQL_VALIDATE: V1OrgOrgIdCqlValidate,
        PathValues.V1_ORG_ORG_ID_CQL_EVALUATE: V1OrgOrgIdCqlEvaluate,
        PathValues.V1_ORG_ORG_ID_FIELD: V1OrgOrgIdField,
        PathValues.V1_ORG_ORG_ID_FIELD_FIELD_ID: V1OrgOrgIdFieldFieldId,
        PathValues.V1_ORG_ORG_ID_FIELD_REMOVEOVERRIDES: V1OrgOrgIdFieldRemoveOverrides,
        PathValues.V1_ORG_ORG_ID_FIELD_REMOVECATEGORY: V1OrgOrgIdFieldRemoveCategory,
        PathValues.V1_ORG_ORG_ID_FIELD_FIELD_ID_DRYRUN: V1OrgOrgIdFieldFieldIdDryrun,
        PathValues.V1_ORG_ORG_ID_FIELD_DELETE: V1OrgOrgIdFieldDelete,
        PathValues.V1_ORG_ORG_ID_FIELD_BUILTIN: V1OrgOrgIdFieldBuiltIn,
        PathValues.V1_ORG_ORG_ID_FIELD_CATEGORY_CATEGORY_ID: V1OrgOrgIdFieldCategoryCategoryId,
        PathValues.V1_ORG_ORG_ID_FIELD_CATEGORY: V1OrgOrgIdFieldCategory,
        PathValues.V1_ORG_ORG_ID_FIELD_STATUS: V1OrgOrgIdFieldStatus,
        PathValues.V1_ORG_ORG_ID_FILE: V1OrgOrgIdFile,
        PathValues.V1_ORG_ORG_ID_FILE_FILE_ID: V1OrgOrgIdFileFileId,
        PathValues.V1_ORG_ORG_ID_FILE_FILE_ID_DOWNLOAD: V1OrgOrgIdFileFileIdDownload,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID: V1OrgOrgIdFormFormId,
        PathValues.V1_ORG_ORG_ID_FORM_DELETE: V1OrgOrgIdFormDelete,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_DRAFT: V1OrgOrgIdFormFormIdDraft,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_SUBMIT_DRAFT: V1OrgOrgIdFormFormIdSubmitDraft,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_SUBMIT: V1OrgOrgIdFormFormIdSubmit,
        PathValues.V1_ORG_ORG_ID_FORM_AVAILABLE: V1OrgOrgIdFormAvailable,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_RENDER: V1OrgOrgIdFormFormIdRender,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_RERENDER_QUESTION_UPDATE_QUESTION_ID: V1OrgOrgIdFormFormIdRerenderQuestionUpdateQuestionId,
        PathValues.V1_ORG_ORG_ID_FORM_DRAFT_DRAFT_ID: V1OrgOrgIdFormDraftDraftId,
        PathValues.V1_ORG_ORG_ID_FORM: V1OrgOrgIdForm,
        PathValues.V1_ORG_ORG_ID_FORM_PERSON_PERSON_ID: V1OrgOrgIdFormPersonPersonId,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_COLLECT: V1OrgOrgIdFormFormIdCollect,
        PathValues.V1_ORG_ORG_ID_FORM_FORM_ID_REMIND: V1OrgOrgIdFormFormIdRemind,
        PathValues.V1_ORG_ORG_ID_FORM_STATUS: V1OrgOrgIdFormStatus,
        PathValues.V1_ORG_ORG_ID_FORMRESPONSE_FORM_RESPONSE_ID: V1OrgOrgIdFormResponseFormResponseId,
        PathValues.V1_ORG_ORG_ID_FORMRESPONSE: V1OrgOrgIdFormResponse,
        PathValues.V1_ORG_ORG_ID_FORMRESPONSE_COUNT: V1OrgOrgIdFormResponseCount,
        PathValues.V1_MEDIA: V1Media,
        PathValues.V1_MEDIA_MEDIA_ID: V1MediaMediaId,
        PathValues.V1_ORG_ORG_ID_GUIDELINE: V1OrgOrgIdGuideline,
        PathValues.V1_ORG_ORG_ID_GUIDELINE_ID: V1OrgOrgIdGuidelineId,
        PathValues.V1_ORG_ORG_ID_GUIDELINE_ID_CALCULATE: V1OrgOrgIdGuidelineIdCalculate,
        PathValues.V1_ORG_ORG_ID_IMPORT_CSV_DATA: V1OrgOrgIdImportCsvData,
        PathValues.V1_ORG_ORG_ID_IMPORT_CSV_COLUMN_MATCH: V1OrgOrgIdImportCsvColumnMatch,
        PathValues.V1_ORG_ORG_ID_IMPORT_CSV_FILEPATH: V1OrgOrgIdImportCsvFilepath,
        PathValues.V1_ORG_ORG_ID_IMPORT_SPREADSHEET_VALIDATE_FORMAT: V1OrgOrgIdImportSpreadsheetValidateFormat,
        PathValues.V1_ORG_ORG_ID_IMPORT_CSV_INITIAL_COLUMN_MATCH: V1OrgOrgIdImportCsvInitialColumnMatch,
        PathValues.V1_ORG_ORG_ID_JOBLEVEL: V1OrgOrgIdJobLevel,
        PathValues.V1_ORG_ORG_ID_JOBLEVEL_JOB_LEVEL_ID: V1OrgOrgIdJobLevelJobLevelId,
        PathValues.V1_LEGALDOC_NAME: V1LegaldocName,
        PathValues.V1_LEGALDOC: V1Legaldoc,
        PathValues.V1_ORG_ORG_ID_MEDIA: V1OrgOrgIdMedia,
        PathValues.V1_ORG_ORG_ID_MEDIA_MEDIA_ID: V1OrgOrgIdMediaMediaId,
        PathValues.V1_ORG_ORG_ID_MESSAGE_MESSAGE_ID: V1OrgOrgIdMessageMessageId,
        PathValues.V1_ORG_ORG_ID_MESSAGE_ME: V1OrgOrgIdMessageMe,
        PathValues.V1_ORG_ORG_ID_MESSAGE: V1OrgOrgIdMessage,
        PathValues.V1_ORG_ORG_ID_MESSAGE_ME_MESSAGE_KEY: V1OrgOrgIdMessageMeMessageKey,
        PathValues.V1_ORG_ORG_ID_MESSAGE_MESSAGE_ID_READ: V1OrgOrgIdMessageMessageIdRead,
        PathValues.V1_ORG_ORG_ID_MESSAGE_BULK_READ: V1OrgOrgIdMessageBulkRead,
        PathValues.V1_ORG_ORG_ID_MESSAGE_BULK_SEEN: V1OrgOrgIdMessageBulkSeen,
        PathValues.V1_ORG_ORG_ID_METRIC: V1OrgOrgIdMetric,
        PathValues.V1_ORG_ORG_ID_MULTIPLIER_MULTIPLIER_ID: V1OrgOrgIdMultiplierMultiplierId,
        PathValues.V1_ORG_ORG_ID_MULTIPLIER: V1OrgOrgIdMultiplier,
        PathValues.V1_ORG_ORG_ID_NOTIFICATION: V1OrgOrgIdNotification,
        PathValues.OAUTH_TOKEN: OauthToken,
        PathValues.OAUTH_APP_APP_NAME: OauthAppAppName,
        PathValues.OAUTH_SSO_IDP_LOGIN: OauthSsoIdpLogin,
        PathValues.OAUTH_SSO_IDP_ACCESSTOKEN: OauthSsoIdpAccessToken,
        PathValues.OAUTH_TOKEN_VIEW: OauthTokenView,
        PathValues.OAUTH_TOKEN_SSO_TYPE: OauthTokenSsoType,
        PathValues.V1_ORG_ORG_ID_ONBOARD: V1OrgOrgIdOnboard,
        PathValues.V1_ORG_ORG_ID_ONBOARD_STEP_NAME_SKIP: V1OrgOrgIdOnboardStepNameSkip,
        PathValues.V1_ORG_ORG_ID_CONFIG: V1OrgOrgIdConfig,
        PathValues.V1_ORG: V1Org,
        PathValues.V1_ORG_ORG_ID: V1OrgOrgId,
        PathValues.V1_ORG_ORG_ID_DATAUSERSPERSONS: V1OrgOrgIdDataUsersPersons,
        PathValues.V1_ORG_ORG_ID_CHANGEHEAD: V1OrgOrgIdChangeHead,
        PathValues.V1_ORG_ORG_ID_WELCOMEEMAIL: V1OrgOrgIdWelcomeEmail,
        PathValues.V1_ORG_ORG_ID_TESTEMAIL: V1OrgOrgIdTestEmail,
        PathValues.V1_ORG_ORG_ID_AGREEMENT: V1OrgOrgIdAgreement,
        PathValues.V1_ORG_ORG_ID_ACCESS: V1OrgOrgIdAccess,
        PathValues.V1_ORG_ORG_ID_DATAUSERPERSONCOUNT: V1OrgOrgIdDataUserPersonCount,
        PathValues.V1_ORG_ORG_ID_DATAUSERPERSON: V1OrgOrgIdDataUserPerson,
        PathValues.V1_ORG_ORG_APPINSTALLCODE: V1OrgOrgAppInstallCode,
        PathValues.V1_ORG_APPINSTALLCODE_VALIDATE: V1OrgAppInstallCodeValidate,
        PathValues.ORG_SLUG: OrgSlug,
        PathValues.V1_ORG_SLUG_SLUG: V1OrgSlugSlug,
        PathValues.V1_ORG_ORG_ID_POLICY_POLICY_ID: V1OrgOrgIdPolicyPolicyId,
        PathValues.V1_ORG_ORG_ID_POLICY: V1OrgOrgIdPolicy,
        PathValues.V1_ORG_ORG_ID_POLICY_POLICY_ID_COPY: V1OrgOrgIdPolicyPolicyIdCopy,
        PathValues.V1_ORG_ORG_ID_POLICY_VALIDATE: V1OrgOrgIdPolicyValidate,
        PathValues.V1_ORG_ORG_ID_POLICY_ACTION: V1OrgOrgIdPolicyAction,
        PathValues.V1_ORG_ORG_ID_PRELOAD: V1OrgOrgIdPreload,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_DECREMENT: V1OrgOrgIdProcessProcessIdDecrement,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_INCREMENT: V1OrgOrgIdProcessProcessIdIncrement,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_RESUME: V1OrgOrgIdProcessProcessIdResume,
        PathValues.V1_ORG_ORG_ID_PROCESS: V1OrgOrgIdProcess,
        PathValues.V1_ORG_ORG_ID_PROCESS_SELFSERVE: V1OrgOrgIdProcessSelfServe,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_STATE: V1OrgOrgIdProcessProcessIdState,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_RESUME_WITH_FILE: V1OrgOrgIdProcessProcessIdResumeWithFile,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_EVENTS: V1OrgOrgIdProcessProcessIdEvents,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_FILE: V1OrgOrgIdProcessProcessIdFile,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID_LOG: V1OrgOrgIdProcessProcessIdLog,
        PathValues.V1_ORG_ORG_ID_PROCESS_PROCESS_ID: V1OrgOrgIdProcessProcessId,
        PathValues.V1_ORG_ORG_ID_PROCESS_LASTSYNC_APP_USER_ID: V1OrgOrgIdProcessLastSyncAppUserId,
        PathValues.V1_ORG_ORG_ID_PROCESS_CREATE_ID_OVERRIDE: V1OrgOrgIdProcessCreateIdOverride,
        PathValues.V1_PRODUCT_PRODUCT_ID: V1ProductProductId,
        PathValues.V1_PRODUCT: V1Product,
        PathValues.V1_ORG_ORG_ID_PROFILETAB_JOB_JOB_ID_PROFILETAB_TAB_ID: V1OrgOrgIdProfileTabJobJobIdProfileTabTabId,
        PathValues.V1_ORG_ORG_ID_PROFILETAB_PROFILE_TAB_ID: V1OrgOrgIdProfileTabProfileTabId,
        PathValues.V1_ORG_ORG_ID_PROFILETAB: V1OrgOrgIdProfileTab,
        PathValues.V1_ORG_ORG_ID_PROFILETAB_PERSON_PERSON_ID: V1OrgOrgIdProfileTabPersonPersonId,
        PathValues.V1_ORG_ORG_ID_PROFILETAB_JOB_JOB_ID: V1OrgOrgIdProfileTabJobJobId,
        PathValues.V1_ORG_ORG_ID_QUERY_QUERY_TOKEN: V1OrgOrgIdQueryQueryToken,
        PathValues.V1_ORG_ORG_ID_QUERY: V1OrgOrgIdQuery,
        PathValues.V1_ORG_ORG_ID_QUESTION_QUESTION_ID: V1OrgOrgIdQuestionQuestionId,
        PathValues.V1_ORG_ORG_ID_QUESTION: V1OrgOrgIdQuestion,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_CHART: V1OrgOrgIdReportReportIdChart,
        PathValues.V1_ORG_ORG_ID_REPORT_CHART_CHART_ID: V1OrgOrgIdReportChartChartId,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_CHART_CHART_ID_CLONE: V1OrgOrgIdReportReportIdChartChartIdClone,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_CHART_CHART_ID_DATA: V1OrgOrgIdReportReportIdChartChartIdData,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_CHART_CHART_ID_QUERY: V1OrgOrgIdReportReportIdChartChartIdQuery,
        PathValues.V1_ORG_ORG_ID_REPORT: V1OrgOrgIdReport,
        PathValues.V1_ORG_ORG_ID_REPORT_COUNT: V1OrgOrgIdReportCount,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID: V1OrgOrgIdReportReportId,
        PathValues.V1_ORG_ORG_ID_REPORT_QUERY: V1OrgOrgIdReportQuery,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_QUERY: V1OrgOrgIdReportReportIdQuery,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_CHART_CHART_ID_EXPORT_CSV: V1OrgOrgIdReportReportIdChartChartIdExportCsv,
        PathValues.V1_ORG_ORG_ID_REPORT_REPORT_ID_CLONE: V1OrgOrgIdReportReportIdClone,
        PathValues.V1_ORG_ORG_ID_REPORT_BULKDELETE: V1OrgOrgIdReportBulkDelete,
        PathValues.V1_ORG_ORG_ID_REPORT_BULKDUPLICATE: V1OrgOrgIdReportBulkDuplicate,
        PathValues.V1_ORG_ORG_ID_ROLE: V1OrgOrgIdRole,
        PathValues.V1_ORG_ORG_ID_ROLE_ROLE_ID: V1OrgOrgIdRoleRoleId,
        PathValues.V1_ORG_ORG_ID_ROLE_ROLE_ID_COPY: V1OrgOrgIdRoleRoleIdCopy,
        PathValues.SAML_ORG_LOGIN: SamlOrgLogin,
        PathValues.SAML_SSO_ORG: SamlSsoOrg,
        PathValues.SAML_ORG_ORG_ID_XMLCERT: SamlOrgOrgIdXmlCert,
        PathValues.V1_ORG_ORG_ID_SCENARIO_BULK_ARCHIVE: V1OrgOrgIdScenarioBulkArchive,
        PathValues.V1_ORG_ORG_ID_SCENARIO_BULK_DELETE: V1OrgOrgIdScenarioBulkDelete,
        PathValues.V1_ORG_ORG_ID_SCENARIO_BULK_UNARCHIVE: V1OrgOrgIdScenarioBulkUnarchive,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID: V1OrgOrgIdScenarioScenarioId,
        PathValues.V1_ORG_ORG_ID_SCENARIO: V1OrgOrgIdScenario,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_DATES: V1OrgOrgIdScenarioScenarioIdDates,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_MERGE: V1OrgOrgIdScenarioScenarioIdMerge,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_COMBINE: V1OrgOrgIdScenarioScenarioIdCombine,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_RECALCULATEMETADATA: V1OrgOrgIdScenarioScenarioIdRecalculateMetadata,
        PathValues.V1_ORG_ORG_ID_SCENARIO_SCENARIO_ID_UPDATESHAREDVIEW: V1OrgOrgIdScenarioScenarioIdUpdateSharedView,
        PathValues.V1_ORG_ORG_ID_SEARCH: V1OrgOrgIdSearch,
        PathValues.V1_STATUS: V1Status,
        PathValues.V1_STOCK: V1Stock,
        PathValues.V1_STOCK_ID: V1StockId,
        PathValues.V1_STOCK_SYMBOL_DATE_TYPE: V1StockSymbolDateType,
        PathValues.V1_STRIPE_SETUPINTENT: V1StripeSetupIntent,
        PathValues.V1_STRIPE_PLAN: V1StripePlan,
        PathValues.V1_STRIPE_WEBHOOK: V1StripeWebhook,
        PathValues.V1_STRIPE_PRODUCT_PRODUCT_ID: V1StripeProductProductId,
        PathValues.V1_STRIPE_PRODUCT: V1StripeProduct,
        PathValues.V1_ORG_ORG_ID_TABLE_TABLE_ID: V1OrgOrgIdTableTableId,
        PathValues.V1_ORG_ORG_ID_TABLE_TABLE_ID_IMPORT: V1OrgOrgIdTableTableIdImport,
        PathValues.V1_ORG_ORG_ID_TABLE: V1OrgOrgIdTable,
        PathValues.V1_ORG_ORG_ID_TABLE_TABLE_ID_DATA: V1OrgOrgIdTableTableIdData,
        PathValues.V1_ORG_ORG_ID_TABLE_TABLE_ID_DATA_KEY_COLUMN_KEY_VALUE: V1OrgOrgIdTableTableIdDataKeyColumnKeyValue,
        PathValues.V1_ORG_ORG_ID_TABLE_TABLE_ID_DATA_KEY_COLUMN_KEY_VALUE_PURGE: V1OrgOrgIdTableTableIdDataKeyColumnKeyValuePurge,
        PathValues.V1_ORG_ORG_ID_TABLE_TABLE_ID_EXPORT: V1OrgOrgIdTableTableIdExport,
        PathValues.V1_ORG_ORG_ID_TASKCONFIG: V1OrgOrgIdTaskConfig,
        PathValues.V1_ORG_ORG_ID_TASKCONFIG_ID: V1OrgOrgIdTaskConfigId,
        PathValues.V1_ORG_ORG_ID_TASK_TASK_ID_MARKDONE: V1OrgOrgIdTaskTaskIdMarkDone,
        PathValues.V1_ORG_ORG_ID_TASK_TASK_ID_SKIP: V1OrgOrgIdTaskTaskIdSkip,
        PathValues.V1_ORG_ORG_ID_TASK: V1OrgOrgIdTask,
        PathValues.V1_ORG_ORG_ID_TASK_TASK: V1OrgOrgIdTaskTask,
        PathValues.V1_ORG_ORG_ID_TASK_ME: V1OrgOrgIdTaskMe,
        PathValues.V1_ORG_ORG_ID_TASK_REMIND: V1OrgOrgIdTaskRemind,
        PathValues.V1_ORG_ORG_ID_TASK_TASK_ID: V1OrgOrgIdTaskTaskId,
        PathValues.V1_ORG_ORG_ID_TASK_BULKDELETE: V1OrgOrgIdTaskBulkDelete,
        PathValues.V1_ORG_ORG_ID_TASK_ASSESSMENT_ID_FORM_ID: V1OrgOrgIdTaskAssessmentIdFormId,
        PathValues.V1_ORG_ORG_ID_TASK_SUMMARY_ASSESSMENT_ID: V1OrgOrgIdTaskSummaryAssessmentId,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_BULK_DELETE: V1OrgOrgIdTemplateBulkDelete,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_BULK_DUPLICATE: V1OrgOrgIdTemplateBulkDuplicate,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_TEMPLATE_ID: V1OrgOrgIdTemplateTemplateId,
        PathValues.V1_ORG_ORG_ID_TEMPLATE: V1OrgOrgIdTemplate,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_TEMPLATE_ID_RENDER: V1OrgOrgIdTemplateTemplateIdRender,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_TEMPLATE_ID_PREVIEW: V1OrgOrgIdTemplateTemplateIdPreview,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_TEMPLATE_ID_GENERATE: V1OrgOrgIdTemplateTemplateIdGenerate,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_EMAIL_TEMPLATE_NAME: V1OrgOrgIdTemplateEmailTemplateName,
        PathValues.V1_ORG_ORG_ID_TEMPLATE_EMAIL: V1OrgOrgIdTemplateEmail,
        PathValues.V1_ORG_ORG_ID_TIMEOFF_REQUEST_VALIDATE: V1OrgOrgIdTimeoffRequestValidate,
        PathValues.V1_ORG_ORG_ID_TIMEOFF: V1OrgOrgIdTimeoff,
        PathValues.V1_ORG_ORG_ID_TIMEOFF_TIME_OFF_ID: V1OrgOrgIdTimeoffTimeOffId,
        PathValues.V1_ORG_ORG_ID_TIMEOFF_REQUEST: V1OrgOrgIdTimeoffRequest,
        PathValues.V1_ORG_ORG_ID_TIMEOFF_TIME_OFF_ID_APPROVE: V1OrgOrgIdTimeoffTimeOffIdApprove,
        PathValues.V1_ORG_ORG_ID_TIMEOFF_TIME_OFF_ID_REJECT: V1OrgOrgIdTimeoffTimeOffIdReject,
        PathValues.V1_ORG_ORG_ID_USAGE_TYPE: V1OrgOrgIdUsageType,
        PathValues.V1_USER_USER_ID: V1UserUserId,
        PathValues.V1_USER: V1User,
        PathValues.V1_USER_USER_ID_TOKEN: V1UserUserIdToken,
        PathValues.V1_USER_TOKEN: V1UserToken,
        PathValues.V1_USER_ASSIGN: V1UserAssign,
        PathValues.V1_USER_ME: V1UserMe,
        PathValues.V1_USER_ME_VIEW: V1UserMeView,
        PathValues.V1_USER_EMAIL_EMAIL: V1UserEmailEmail,
        PathValues.V1_USER_PERSON_PERSON_ID: V1UserPersonPersonId,
        PathValues.V1_USER_INVITE: V1UserInvite,
        PathValues.V1_USER_USER_ID_PASSWORD: V1UserUserIdPassword,
        PathValues.V1_USER_SENDRESET: V1UserSendreset,
        PathValues.V1_WEBAUTHN_REGISTER: V1WebauthnRegister,
        PathValues.V1_WEBAUTHN_REGISTER_EMAIL_BASE64: V1WebauthnRegisterEmailBase64,
        PathValues.V1_WEBAUTHN_VERIFY: V1WebauthnVerify,
        PathValues.V2_ORG_ORG_ID_CHANGE_CHANGE_ID: V2OrgOrgIdChangeChangeId,
        PathValues.V2_ORG_ORG_ID_CHANGE: V2OrgOrgIdChange,
        PathValues.V2_ORG_ORG_ID_GROUP_TYPE: V2OrgOrgIdGroupType,
        PathValues.V2_ORG_ORG_ID_GROUP_TYPE_GROUP_ID: V2OrgOrgIdGroupTypeGroupId,
        PathValues.V2_ORG_ORG_ID_GROUP_COUNT: V2OrgOrgIdGroupCount,
        PathValues.V2_ORG_ORG_ID_GROUP_TYPE_BULKDELETE: V2OrgOrgIdGroupTypeBulkDelete,
        PathValues.V2_ORG_ORG_ID_GROUP_TYPE_IMPORT: V2OrgOrgIdGroupTypeImport,
        PathValues.V2_ORG_ORG_ID_GROUP_GRAPH: V2OrgOrgIdGroupGraph,
        PathValues.V2_ORG_ORG_ID_GROUP_ORPHANED: V2OrgOrgIdGroupOrphaned,
        PathValues.V2_ORG_ORG_ID_JOB_JOB_ID: V2OrgOrgIdJobJobId,
        PathValues.V2_ORG_ORG_ID_JOB_COUNT: V2OrgOrgIdJobCount,
        PathValues.V2_ORG_ORG_ID_JOB_BULKUPDATE: V2OrgOrgIdJobBulkupdate,
        PathValues.V2_ORG_ORG_ID_JOB_GRAPH: V2OrgOrgIdJobGraph,
        PathValues.V2_ORG_ORG_ID_JOB_GRAPHCOUNTS: V2OrgOrgIdJobGraphCounts,
        PathValues.V2_ORG_ORG_ID_JOB: V2OrgOrgIdJob,
        PathValues.V2_ORG_ORG_ID_JOB_JOB_ID_POSITION: V2OrgOrgIdJobJobIdPosition,
        PathValues.V2_ORG_ORG_ID_PERSON: V2OrgOrgIdPerson,
        PathValues.V2_ORG_ORG_ID_PERSON_PERSON_ID: V2OrgOrgIdPersonPersonId,
        PathValues.V2_ORG_ORG_ID_PERSON_GEOCODES: V2OrgOrgIdPersonGeocodes,
        PathValues.V2_ORG_ORG_ID_POSITION_POSITION_ID: V2OrgOrgIdPositionPositionId,
        PathValues.V2_ORG_ORG_ID_POSITION_POSITION_ID_HISTORY: V2OrgOrgIdPositionPositionIdHistory,
        PathValues.V2_ORG_ORG_ID_POSITION: V2OrgOrgIdPosition,
        PathValues.V2_ORG_ORG_ID_POSITION_POSITION_ID_PURGE: V2OrgOrgIdPositionPositionIdPurge,
        PathValues.V2_ORG_ORG_ID_POSITION_POSITION_ID_JOB_JOB_ID: V2OrgOrgIdPositionPositionIdJobJobId,
        PathValues.V2_ORG_ORG_ID_POSITION_IMPORT: V2OrgOrgIdPositionImport,
    }
)
