# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_action.post import CreateNewAction
from chart_hop_python_sdk.paths.v1_org_org_id_action_action_id.delete import DeleteActionById
from chart_hop_python_sdk.paths.v1_org_org_id_action_action_id_run.post import ExecuteActionForTesting
from chart_hop_python_sdk.paths.v1_org_org_id_action_action_id.get import GetActionById
from chart_hop_python_sdk.paths.v1_org_org_id_action.get import GetAllPaginated
from chart_hop_python_sdk.paths.v1_org_org_id_action_action_id.patch import UpdateExistingActionById
from chart_hop_python_sdk.apis.tags.action_api_raw import ActionApiRaw


class ActionApi(
    CreateNewAction,
    DeleteActionById,
    ExecuteActionForTesting,
    GetActionById,
    GetAllPaginated,
    UpdateExistingActionById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ActionApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ActionApiRaw(api_client)
