# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_app_config.post import CreateNewConfig
from chart_hop_python_sdk.paths.v1_app_config_app_id.get import GetDefaultConfigByApp
from chart_hop_python_sdk.paths.v1_app_config_app_id_user_id.get import GetUserConfigByAppAndUser
from chart_hop_python_sdk.paths.v1_app_config_app_id_user_id.patch import UpdateById
from chart_hop_python_sdk.apis.tags.app_config_api_raw import AppConfigApiRaw


class AppConfigApi(
    CreateNewConfig,
    GetDefaultConfigByApp,
    GetUserConfigByAppAndUser,
    UpdateById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AppConfigApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AppConfigApiRaw(api_client)
