# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_exchange_rate_date_custom_bulkupdate.post import BulkUpdateCustomRatesRaw
from chart_hop_python_sdk.paths.v1_org_org_id_exchange_rate_date.delete import DeleteCustomRateOnDateRaw
from chart_hop_python_sdk.paths.v1_org_org_id_exchange_rate_date_custom.get import GetCustomExchangeRatesRaw
from chart_hop_python_sdk.paths.v1_org_org_id_exchange_rate_date_global.get import GetGlobalByDateRaw
from chart_hop_python_sdk.paths.v1_org_org_id_exchange_rate_date.get import GetRatesOnDateRaw
from chart_hop_python_sdk.paths.v1_org_org_id_exchange_rate_date_history.get import OrgCustomExchangeRatesHistoryRaw
from chart_hop_python_sdk.paths.v1_org_org_id_exchange_rate_date.patch import UpdateUsdExchangeRatesForDateRaw


class ExchangeRateApiRaw(
    BulkUpdateCustomRatesRaw,
    DeleteCustomRateOnDateRaw,
    GetCustomExchangeRatesRaw,
    GetGlobalByDateRaw,
    GetRatesOnDateRaw,
    OrgCustomExchangeRatesHistoryRaw,
    UpdateUsdExchangeRatesForDateRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
