# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_change.post import ChangelogToCsv
from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_fields.post import CsvCustomFields
from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_scenario_scenario_id_comments.post import CsvScenarioComments
from chart_hop_python_sdk.paths.v1_org_org_id_export_zip_file.post import FileZipDownload
from chart_hop_python_sdk.paths.v1_org_org_id_export_powerpoint_org.post import OrgChartToPowerpoint
from chart_hop_python_sdk.paths.v1_org_org_id_export_pdf_review_assessment_id.post import PdfReview
from chart_hop_python_sdk.paths.v1_org_org_id_export_powerpoint_report_report_id.post import ReportToPowerpoint
from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_snapshot.post import RosterToCsvSnapshot
from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_scenario_scenario_id.post import ScenarioCsv
from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_task_review_id.post import TaskToCsv
from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_users.post import UserReviewCsv
from chart_hop_python_sdk.apis.tags.export_api_raw import ExportApiRaw


class ExportApi(
    ChangelogToCsv,
    CsvCustomFields,
    CsvScenarioComments,
    FileZipDownload,
    OrgChartToPowerpoint,
    PdfReview,
    ReportToPowerpoint,
    RosterToCsvSnapshot,
    ScenarioCsv,
    TaskToCsv,
    UserReviewCsv,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ExportApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ExportApiRaw(api_client)
