# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_change.post import ChangelogToCsvRaw
from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_fields.post import CsvCustomFieldsRaw
from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_scenario_scenario_id_comments.post import CsvScenarioCommentsRaw
from chart_hop_python_sdk.paths.v1_org_org_id_export_zip_file.post import FileZipDownloadRaw
from chart_hop_python_sdk.paths.v1_org_org_id_export_powerpoint_org.post import OrgChartToPowerpointRaw
from chart_hop_python_sdk.paths.v1_org_org_id_export_pdf_review_assessment_id.post import PdfReviewRaw
from chart_hop_python_sdk.paths.v1_org_org_id_export_powerpoint_report_report_id.post import ReportToPowerpointRaw
from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_snapshot.post import RosterToCsvSnapshotRaw
from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_scenario_scenario_id.post import ScenarioCsvRaw
from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_task_review_id.post import TaskToCsvRaw
from chart_hop_python_sdk.paths.v1_org_org_id_export_csv_users.post import UserReviewCsvRaw


class ExportApiRaw(
    ChangelogToCsvRaw,
    CsvCustomFieldsRaw,
    CsvScenarioCommentsRaw,
    FileZipDownloadRaw,
    OrgChartToPowerpointRaw,
    PdfReviewRaw,
    ReportToPowerpointRaw,
    RosterToCsvSnapshotRaw,
    ScenarioCsvRaw,
    TaskToCsvRaw,
    UserReviewCsvRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
