# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_form.post import CreateNewForm
from chart_hop_python_sdk.paths.v1_org_org_id_form_form_id.delete import DeleteFormById
from chart_hop_python_sdk.paths.v1_org_org_id_form_delete.delete import DeleteFormById0
from chart_hop_python_sdk.paths.v1_org_org_id_form_draft_draft_id.delete import DeleteFormDraft
from chart_hop_python_sdk.paths.v1_org_org_id_form_person_person_id.get import GetApplicableFormsForPerson
from chart_hop_python_sdk.paths.v1_org_org_id_form_form_id.get import GetById
from chart_hop_python_sdk.paths.v1_org_org_id_form_form_id_draft.get import GetCurrentStateOfDraftData
from chart_hop_python_sdk.paths.v1_org_org_id_form_available.get import ListAvailableForms
from chart_hop_python_sdk.paths.v1_org_org_id_form.get import ListOrgForms
from chart_hop_python_sdk.paths.v1_org_org_id_form_form_id_render.get import RenderForDisplay
from chart_hop_python_sdk.paths.v1_org_org_id_form_form_id_rerender_question_update_question_id.post import RerenderQuestionUpdate
from chart_hop_python_sdk.paths.v1_org_org_id_form_form_id_collect.post import SendEmailsAndChatNotifications
from chart_hop_python_sdk.paths.v1_org_org_id_form_form_id_remind.post import SendReminderNotification
from chart_hop_python_sdk.paths.v1_org_org_id_form_form_id_draft.post import SubmitDraftData
from chart_hop_python_sdk.paths.v1_org_org_id_form_form_id_submit.post import SubmitFormData
from chart_hop_python_sdk.paths.v1_org_org_id_form_form_id_submit_draft.post import SubmitFormDraft
from chart_hop_python_sdk.paths.v1_org_org_id_form_form_id.post import SubmitFormResponse
from chart_hop_python_sdk.paths.v1_org_org_id_form_form_id.patch import UpdateExistingForm
from chart_hop_python_sdk.paths.v1_org_org_id_form_status.post import UpdateFormStatus
from chart_hop_python_sdk.apis.tags.form_api_raw import FormApiRaw


class FormApi(
    CreateNewForm,
    DeleteFormById,
    DeleteFormById0,
    DeleteFormDraft,
    GetApplicableFormsForPerson,
    GetById,
    GetCurrentStateOfDraftData,
    ListAvailableForms,
    ListOrgForms,
    RenderForDisplay,
    RerenderQuestionUpdate,
    SendEmailsAndChatNotifications,
    SendReminderNotification,
    SubmitDraftData,
    SubmitFormData,
    SubmitFormDraft,
    SubmitFormResponse,
    UpdateExistingForm,
    UpdateFormStatus,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FormApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FormApiRaw(api_client)
