# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v2_org_org_id_group_type.post import CreateNewGroupRaw
from chart_hop_python_sdk.paths.v2_org_org_id_group_graph.get import FindInOrgOfTypeRaw
from chart_hop_python_sdk.paths.v2_org_org_id_group_type.get import FindOfTypeRaw
from chart_hop_python_sdk.paths.v2_org_org_id_group_orphaned.get import FindOrphanedGroupsRaw
from chart_hop_python_sdk.paths.v2_org_org_id_group_type_group_id.get import GetByIdRaw
from chart_hop_python_sdk.paths.v2_org_org_id_group_count.get import GetOrganizedGroupCountsRaw
from chart_hop_python_sdk.paths.v2_org_org_id_group_type_import.post import ImportCsvDataRaw
from chart_hop_python_sdk.paths.v2_org_org_id_group_type_bulk_delete.post import MarkMultipleAsDeletedRaw
from chart_hop_python_sdk.paths.v2_org_org_id_group_type_group_id.delete import RemoveByGroupIdRaw
from chart_hop_python_sdk.paths.v2_org_org_id_group_type_group_id.patch import UpdateGroupDetailsRaw


class GroupApiRaw(
    CreateNewGroupRaw,
    FindInOrgOfTypeRaw,
    FindOfTypeRaw,
    FindOrphanedGroupsRaw,
    GetByIdRaw,
    GetOrganizedGroupCountsRaw,
    ImportCsvDataRaw,
    MarkMultipleAsDeletedRaw,
    RemoveByGroupIdRaw,
    UpdateGroupDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
