# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_guideline.get import AllForCompReview
from chart_hop_python_sdk.paths.v1_org_org_id_guideline_id_calculate.get import CalculateMatrixValuesForSpecificGuideline
from chart_hop_python_sdk.paths.v1_org_org_id_guideline.post import CreateNewGuideline
from chart_hop_python_sdk.paths.v1_org_org_id_guideline_id.get import GetSpecificGuideline
from chart_hop_python_sdk.paths.v1_org_org_id_guideline_id.delete import RemoveById
from chart_hop_python_sdk.paths.v1_org_org_id_guideline_id.patch import UpdateGuideline
from chart_hop_python_sdk.apis.tags.guideline_api_raw import GuidelineApiRaw


class GuidelineApi(
    AllForCompReview,
    CalculateMatrixValuesForSpecificGuideline,
    CreateNewGuideline,
    GetSpecificGuideline,
    RemoveById,
    UpdateGuideline,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: GuidelineApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = GuidelineApiRaw(api_client)
