# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_agreement.post import ConsentTermsOfServiceRaw
from chart_hop_python_sdk.paths.v1_org_org_id_change_head.post import CreateNewJobPlaceholderRaw
from chart_hop_python_sdk.paths.v1_org.post import CreateNewOrgRaw
from chart_hop_python_sdk.paths.v1_org_org_id.get import GetByIdRaw
from chart_hop_python_sdk.paths.v1_org_slug_slug.get import GetBySlugRaw
from chart_hop_python_sdk.paths.v1_org_org_id_data_user_person.get import GetDataUserPersonByIdRaw
from chart_hop_python_sdk.paths.v1_org_org_id_data_user_person_count.get import GetDataUserPersonCountRaw
from chart_hop_python_sdk.paths.v1_org_org_id_data_users_persons.get import GetDataUsersPersonsRaw
from chart_hop_python_sdk.paths.v1_org_org_app_install_code.post import GetOauth2AuthorizationCodeRaw
from chart_hop_python_sdk.paths.v1_org_org_id_access.get import GetUserAccessRaw
from chart_hop_python_sdk.paths.org_slug.get import GetValidationBySlugRaw
from chart_hop_python_sdk.paths.v1_org_org_id_welcome_email.get import GetWelcomeEmailSettingsRaw
from chart_hop_python_sdk.paths.v1_org.get import ListVisibleOrgsRaw
from chart_hop_python_sdk.paths.v1_org_org_id_test_email.post import SendTestEmailToOneselfRaw
from chart_hop_python_sdk.paths.v1_org_org_id.patch import UpdateExistingOrgRaw
from chart_hop_python_sdk.paths.v1_org_app_install_code_validate.post import ValidateAppInstallAuthorizationCodeRaw


class OrgApiRaw(
    ConsentTermsOfServiceRaw,
    CreateNewJobPlaceholderRaw,
    CreateNewOrgRaw,
    GetByIdRaw,
    GetBySlugRaw,
    GetDataUserPersonByIdRaw,
    GetDataUserPersonCountRaw,
    GetDataUsersPersonsRaw,
    GetOauth2AuthorizationCodeRaw,
    GetUserAccessRaw,
    GetValidationBySlugRaw,
    GetWelcomeEmailSettingsRaw,
    ListVisibleOrgsRaw,
    SendTestEmailToOneselfRaw,
    UpdateExistingOrgRaw,
    ValidateAppInstallAuthorizationCodeRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
