# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_config.post import CreateIfNotExistsRaw
from chart_hop_python_sdk.paths.v1_org_org_id_config.get import GetByOrgIdRaw
from chart_hop_python_sdk.paths.v1_org_org_id_config.patch import PatchExistingConfigRaw


class OrgConfigApiRaw(
    CreateIfNotExistsRaw,
    GetByOrgIdRaw,
    PatchExistingConfigRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
