# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_process_process_id.get import CheckProcessStatusRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process.post import CreateNewPendingProcessRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_self_serve.post import CreatePendingProcessRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_create_id_override.post import CreatePendingProcessWithUserIdRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_process_id_decrement.put import DecrementStepRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_process_id_file.get import DownloadFileByIdRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_process_id_log.get import DownloadLogRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_process_id_events.get import GetEventsByProcessIdRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_last_sync_app_user_id.get import GetLastSyncForAppUserRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process.get import GetPreviouslyRunProcessesRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_process_id_increment.put import IncrementProcessStepRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_process_id_resume.put import ResumeProcessWithUserIdRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_process_id_resume_with_file.put import ResumeWithFileRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_process_id_state.put import UpdateProcessStateRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_process_id.patch import UpdateStatusOfProcessRaw
from chart_hop_python_sdk.paths.v1_org_org_id_process_process_id_file.post import UploadFileAndMarkCompleteRaw


class ProcessApiRaw(
    CheckProcessStatusRaw,
    CreateNewPendingProcessRaw,
    CreatePendingProcessRaw,
    CreatePendingProcessWithUserIdRaw,
    DecrementStepRaw,
    DownloadFileByIdRaw,
    DownloadLogRaw,
    GetEventsByProcessIdRaw,
    GetLastSyncForAppUserRaw,
    GetPreviouslyRunProcessesRaw,
    IncrementProcessStepRaw,
    ResumeProcessWithUserIdRaw,
    ResumeWithFileRaw,
    UpdateProcessStateRaw,
    UpdateStatusOfProcessRaw,
    UploadFileAndMarkCompleteRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
