# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_profile_tab.post import CreateNewTab
from chart_hop_python_sdk.paths.v1_org_org_id_profile_tab_profile_tab_id.delete import DeleteProfileTab
from chart_hop_python_sdk.paths.v1_org_org_id_profile_tab_job_job_id.get import FindTabsForJob
from chart_hop_python_sdk.paths.v1_org_org_id_profile_tab_profile_tab_id.get import GetByOrgIdAndTabId
from chart_hop_python_sdk.paths.v1_org_org_id_profile_tab_job_job_id_profile_tab_tab_id.get import GetEvaluateProfileTabContent
from chart_hop_python_sdk.paths.v1_org_org_id_profile_tab_person_person_id.get import GetProfileTabs
from chart_hop_python_sdk.paths.v1_org_org_id_profile_tab.get import ListProfileTabs
from chart_hop_python_sdk.paths.v1_org_org_id_profile_tab_profile_tab_id.patch import UpdateExistingTab
from chart_hop_python_sdk.apis.tags.profile_tab_api_raw import ProfileTabApiRaw


class ProfileTabApi(
    CreateNewTab,
    DeleteProfileTab,
    FindTabsForJob,
    GetByOrgIdAndTabId,
    GetEvaluateProfileTabContent,
    GetProfileTabs,
    ListProfileTabs,
    UpdateExistingTab,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProfileTabApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProfileTabApiRaw(api_client)
