# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_report_report_id_chart_chart_id_clone.post import CloneChart
from chart_hop_python_sdk.paths.v1_org_org_id_report_report_id_chart.post import CreateNewChart
from chart_hop_python_sdk.paths.v1_org_org_id_report_report_id_chart_chart_id_data.get import ExportData
from chart_hop_python_sdk.paths.v1_org_org_id_report_report_id_chart.get import GetAll
from chart_hop_python_sdk.paths.v1_org_org_id_report_chart_chart_id.get import GetByChartId
from chart_hop_python_sdk.paths.v1_org_org_id_report_report_id_chart_chart_id_query.get import QueryUnderlyingDataInChart
from chart_hop_python_sdk.paths.v1_org_org_id_report_chart_chart_id.delete import RemoveById
from chart_hop_python_sdk.paths.v1_org_org_id_report_chart_chart_id.patch import UpdateExistingChartData
from chart_hop_python_sdk.apis.tags.report_chart_api_raw import ReportChartApiRaw


class ReportChartApi(
    CloneChart,
    CreateNewChart,
    ExportData,
    GetAll,
    GetByChartId,
    QueryUnderlyingDataInChart,
    RemoveById,
    UpdateExistingChartData,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ReportChartApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ReportChartApiRaw(api_client)
