# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_report_bulk_delete.post import BulkDelete
from chart_hop_python_sdk.paths.v1_org_org_id_report_report_id_clone.post import CreateExactCopy
from chart_hop_python_sdk.paths.v1_org_org_id_report.post import CreateNewReport
from chart_hop_python_sdk.paths.v1_org_org_id_report_bulk_duplicate.post import DuplicateReports
from chart_hop_python_sdk.paths.v1_org_org_id_report_report_id_chart_chart_id_export_csv.post import ExportChartCsv
from chart_hop_python_sdk.paths.v1_org_org_id_report_report_id.get import FindReportById
from chart_hop_python_sdk.paths.v1_org_org_id_report.get import GetAllPaginated
from chart_hop_python_sdk.paths.v1_org_org_id_report_report_id_query.get import GetAllReportCharts
from chart_hop_python_sdk.paths.v1_org_org_id_report_count.get import GetCountOfReportsInOrganization
from chart_hop_python_sdk.paths.v1_org_org_id_report_report_id.delete import RemoveById
from chart_hop_python_sdk.paths.v1_org_org_id_report_query.post import TimeseriesDataArbitraryQueries
from chart_hop_python_sdk.paths.v1_org_org_id_report_report_id.patch import UpdateExistingReport
from chart_hop_python_sdk.apis.tags.report_api_raw import ReportApiRaw


class ReportApi(
    BulkDelete,
    CreateExactCopy,
    CreateNewReport,
    DuplicateReports,
    ExportChartCsv,
    FindReportById,
    GetAllPaginated,
    GetAllReportCharts,
    GetCountOfReportsInOrganization,
    RemoveById,
    TimeseriesDataArbitraryQueries,
    UpdateExistingReport,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ReportApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ReportApiRaw(api_client)
