# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_scenario_scenario_id_dates.post import AdjustDates
from chart_hop_python_sdk.paths.v1_org_org_id_scenario_bulk_archive.post import BulkArchiveScenarios
from chart_hop_python_sdk.paths.v1_org_org_id_scenario_scenario_id_combine.post import CombineScenarios
from chart_hop_python_sdk.paths.v1_org_org_id_scenario.post import CreateNew
from chart_hop_python_sdk.paths.v1_org_org_id_scenario_bulk_delete.post import DeleteBulkScenarios
from chart_hop_python_sdk.paths.v1_org_org_id_scenario_scenario_id.get import GetById
from chart_hop_python_sdk.paths.v1_org_org_id_scenario.get import ListPaginatedScenarios
from chart_hop_python_sdk.paths.v1_org_org_id_scenario_scenario_id_recalculate_metadata.post import ManuallyRecalculateMetadata
from chart_hop_python_sdk.paths.v1_org_org_id_scenario_scenario_id_merge.post import MergeIntoPrimaryTimeline
from chart_hop_python_sdk.paths.v1_org_org_id_scenario_scenario_id.delete import RemoveById
from chart_hop_python_sdk.paths.v1_org_org_id_scenario_bulk_unarchive.post import UnarchiveSetOfScenarios
from chart_hop_python_sdk.paths.v1_org_org_id_scenario_scenario_id.patch import UpdateScenarioChange
from chart_hop_python_sdk.paths.v1_org_org_id_scenario_scenario_id_update_shared_view.post import UpdateSharedViewConfig
from chart_hop_python_sdk.apis.tags.scenario_api_raw import ScenarioApiRaw


class ScenarioApi(
    AdjustDates,
    BulkArchiveScenarios,
    CombineScenarios,
    CreateNew,
    DeleteBulkScenarios,
    GetById,
    ListPaginatedScenarios,
    ManuallyRecalculateMetadata,
    MergeIntoPrimaryTimeline,
    RemoveById,
    UnarchiveSetOfScenarios,
    UpdateScenarioChange,
    UpdateSharedViewConfig,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ScenarioApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ScenarioApiRaw(api_client)
