# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_org_org_id_task_bulk_delete.delete import DeleteBulkTasksRaw
from chart_hop_python_sdk.paths.v1_org_org_id_task.get import GetAllTasksRaw
from chart_hop_python_sdk.paths.v1_org_org_id_task_summary_assessment_id.get import GetAssessmentTasksSummaryRaw
from chart_hop_python_sdk.paths.v1_org_org_id_task_me.get import GetCurrentUserTasksRaw
from chart_hop_python_sdk.paths.v1_org_org_id_task_task_id_skip.patch import MarkAsSkippedRaw
from chart_hop_python_sdk.paths.v1_org_org_id_task_task.get import QueryAssessmentTasksRaw
from chart_hop_python_sdk.paths.v1_org_org_id_task_task_id.delete import RemoveByIdRaw
from chart_hop_python_sdk.paths.v1_org_org_id_task_assessment_id_form_id.delete import RemoveFormFromAssessmentRaw
from chart_hop_python_sdk.paths.v1_org_org_id_task_remind.post import SendReminderNotificationRaw
from chart_hop_python_sdk.paths.v1_org_org_id_task_task_id_mark_done.patch import UpdateStatusRaw


class TaskApiRaw(
    DeleteBulkTasksRaw,
    GetAllTasksRaw,
    GetAssessmentTasksSummaryRaw,
    GetCurrentUserTasksRaw,
    MarkAsSkippedRaw,
    QueryAssessmentTasksRaw,
    RemoveByIdRaw,
    RemoveFormFromAssessmentRaw,
    SendReminderNotificationRaw,
    UpdateStatusRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
