# coding: utf-8

"""
    ChartHop API

    REST API for ChartHop

    The version of the OpenAPI document: V1.0.0
    Contact: support@charthop.com
    Created by: https://www.charthop.com
"""

from chart_hop_python_sdk.paths.v1_user_assign.patch import AssignRoleToMultipleRaw
from chart_hop_python_sdk.paths.v1_user_user_id_password.post import ChangePasswordRaw
from chart_hop_python_sdk.paths.v1_user.post import CreateNewUserRaw
from chart_hop_python_sdk.paths.v1_user.get import GetAllUsersWithinOrgsRaw
from chart_hop_python_sdk.paths.v1_user_me.get import GetCurrentUserRaw
from chart_hop_python_sdk.paths.v1_user_email_email.get import GetUserByEmailRaw
from chart_hop_python_sdk.paths.v1_user_user_id.get import GetUserByIdRaw
from chart_hop_python_sdk.paths.v1_user_invite.post import InviteMultipleNewUsersRaw
from chart_hop_python_sdk.paths.v1_user_person_person_id.get import ReturnUserByPersonIdRaw
from chart_hop_python_sdk.paths.v1_user_user_id_token.delete import RevokeAccessTokenRaw
from chart_hop_python_sdk.paths.v1_user_token.delete import RevokeAccessTokensRaw
from chart_hop_python_sdk.paths.v1_user_sendreset.post import SendPasswordResetEmailRaw
from chart_hop_python_sdk.paths.v1_user_user_id.patch import UpdateExistingUserRaw
from chart_hop_python_sdk.paths.v1_user_me_view.get import ViewedUserDetailsRaw


class UserApiRaw(
    AssignRoleToMultipleRaw,
    ChangePasswordRaw,
    CreateNewUserRaw,
    GetAllUsersWithinOrgsRaw,
    GetCurrentUserRaw,
    GetUserByEmailRaw,
    GetUserByIdRaw,
    InviteMultipleNewUsersRaw,
    ReturnUserByPersonIdRaw,
    RevokeAccessTokenRaw,
    RevokeAccessTokensRaw,
    SendPasswordResetEmailRaw,
    UpdateExistingUserRaw,
    ViewedUserDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
