from chart_hop_python_sdk.paths.v1_org_org_id_approval_chain_approval_chain_id_request_approval_request_id_reassign_approver.post import ApiForpost


class V1OrgOrgIdApprovalChainApprovalChainIdRequestApprovalRequestIdReassignApprover(
    ApiForpost,
):
    pass
